[package]
name = "macros"
description = "Support macros for flutter_api."
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = { version = "2.0", features = ["full"] }
