[package]
name = "configuration_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "configuration_server"

[lib]
doctest = false

[dependencies]
axum = { workspace = true, features = [
    "http1",
    "tokio",
    "tower-log",
    "tracing",
] }
axum-server = { workspace = true, features = ["tls-rustls"] }
config = { workspace = true, features = ["toml"] }
etag.workspace = true
http.workspace = true
mime.workspace = true
sentry = { workspace = true, features = ["backtrace", "contexts", "debug-images", "panic", "anyhow", "reqwest", "rustls", "tracing", "log"] }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["base64"] }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "parking_lot",
    "macros",
] }
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["parking_lot"] }

wallet_common = { path = "../wallet_common", features = ["sentry"] }
