name: wallet
description: EDI - NL Public Reference Wallet

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  collection: ^1.17.1
  device_info_plus: ^9.0.3
  equatable: ^2.0.5
  ffi: ^2.1.0
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: ^1.81.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_sticky_header: ^0.6.4
  flutter_svg: ^2.0.4
  foil: ^0.9.0+1
  freezed_annotation: ^2.4.1
  golden_toolkit: ^0.15.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.7.1
  meta: ^1.8.0
  mobile_scanner: ^3.4.1
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.3
  qr_flutter: ^4.0.0
  rxdart: ^0.27.5
  screen_brightness: ^0.2.2
  shared_preferences: ^2.2.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.12
  vibration: ^1.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  ffigen: ^8.0.2
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  get_it: ^7.6.0
  mockito: ^5.3.2
  rename: ^2.1.1
  test: ^1.24.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svg/
    - assets/non-free/images/

  fonts:
    - family: RijksoverheidSansWebText
      fonts:
        - asset: assets/non-free/fonts/rijksoverheid-sans-web-text-regular.ttf
          weight: 400
        - asset: assets/non-free/fonts/rijksoverheid-sans-web-text-bold.ttf
          weight: 700
