name: wallet
description: EDI - NL Public Reference Wallet

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  after_layout: ^1.2.0
  app_links: ^3.4.5
  collection: ^1.17.2
  connectivity_plus: ^5.0.1
  country_codes:
    git:
      url: https://github.com/kyle-seongwoo-jun/country_codes.git
      # This (forked) commit includes https://github.com/miguelpruivo/country_codes/pull/29
      # We need those changes to resolve the localized country labels,
      # once it's merged we can fall back to normal country_code package.
      ref: 521ef1c2f1e3756eade396513b7e423664435776
  device_info_plus: ^9.0.3
  equatable: ^2.0.5
  ffi: ^2.1.0
  fimber: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.7
  foil: ^0.9.0+1
  golden_toolkit: ^0.15.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  meta: ^1.9.1
  mobile_scanner: ^3.4.1
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.3
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  screen_brightness: ^0.2.2+1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  vibration: ^1.8.1
  wallet_core:
    path: ./packages/wallet_core
  wallet_mock:
    path: ./packages/wallet_mock

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  get_it: ^7.6.2
  mockito: ^5.4.2
  rename: ^2.1.1
  test: ^1.24.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/non-free/svg/
    - assets/non-free/images/
    - assets/non-free/logos/
    - assets/non-free/fonts/
    - assets/non-free/illustrations/
    - assets/non-free/icons/

  fonts:
    - family: RijksoverheidSansWebText
      fonts:
        - asset: assets/non-free/fonts/rijksoverheid-sans-web-text-regular.ttf
          weight: 400
        - asset: assets/non-free/fonts/rijksoverheid-sans-web-text-bold.ttf
          weight: 700
