[package]
name = "wallet_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[features]
mock = []
software-keys = ["dep:aes-gcm", "dep:once_cell", "dep:rand_core"]
integration-test = []

[dependencies]
aes-gcm = { workspace = true, optional = true, features = ["std"]}
base64.workspace = true
http.workspace = true
jsonwebtoken.workspace = true
once_cell = { workspace = true, optional = true }
p256 = { workspace = true, features = ["ecdsa", "pem", "std"] }
rand.workspace = true
rand_core = { workspace = true, optional = true }
ring.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true

[dev-dependencies]
wallet_common = { path = ".", features = ["software-keys", "integration-test"] }
