[package]
name = "wallet_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[features]
mock = []

[dependencies]
base64.workspace = true
http.workspace = true
jsonwebtoken.workspace = true
p256 = { workspace = true, features = ["ecdsa", "pem", "std"] }
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror.workspace = true
