[package]
name = "wallet_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
mock = []
software-keys = ["dep:aes-gcm", "dep:once_cell", "dep:rand_core"]
integration-test = []

[dependencies]
async-trait.workspace = true
base64.workspace = true
chrono = { workspace = true, features = ["std", "clock"] }
futures.workspace = true
http.workspace = true
jsonwebtoken.workspace = true
p256 = { workspace = true, features = ["ecdsa", "pem", "std"] }
rand.workspace = true
ring.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt"] }

aes-gcm = { workspace = true, optional = true, features = ["std"] }
once_cell = { workspace = true, optional = true }
rand_core = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "parking_lot",
] }

wallet_common = { path = ".", features = ["software-keys", "integration-test"] }
