[workspace]
members = [
    "flutter_api",
    "flutter_api/flutter_api_macros",
    "mdoc",
    "mdoc/fieldnames",
    "mdoc/fieldnames_derive",
    "pid_issuer",
    "platform_support",
    "tests_integration",
    "wallet",
    "wallet/entity",
    "wallet/migration",
    "wallet_common",
    "wallet_provider",
    "wallet_provider/domain",
    "wallet_provider/migration",
    "wallet_provider/persistence",
    "wallet_provider/service",
]
exclude = ["flutter_rust_bridge_codegen", "uniffi-bindgen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

[workspace.dependencies]
aes-gcm = { version = "0.10.1" }
android_logger = { version = "0.13.1" }
anyhow = { version = "1.0.66" }
assert_matches = { version = "1" }
async-trait = { version = "0.1.68" }
axum = { version = "0.6.19", default-features = false }
backtrace = { version = "0.3.67" }
base64 = { version = "0.21.0" }
chrono = { version = "0.4.26", default-features = false }
ciborium = { version = "0.2.1" }
config = { version = "0.13.3", default-features = false }
coset = { version = "0.3.3" }
cryptoki = { version = "0.6.0" }
cstr = { version = "0.2.11" }
ctor = { version = "0.2.5" }
dashmap = { version = "5.4.0" }
der = { version = "0.7.7" }
dotenvy = { version = "0.15.7" }
flutter_rust_bridge = { version = "1.70.0" }
futures = { version = "0.3.17" }
hex = { version = "0.4.3" }
hex-literal = { version = "0.4.1" }
http = { version = "0.2.9" }
indexmap = { version = "2.0.2" }
jni = { version = "0.21.1" }
josekit = { version = "0.8.3" }
jsonwebtoken = { version = "8.2.0" }
libsqlite3-sys = { version = "0.26.0", default-features = false }
mime = { version = "0.3.17" }
mockall = { version = "0.11.4" }
never = { version = "0.1.0" }
once_cell = { version = "1.17.1" }
openid = { version = "0.12.0", default-features = false }
openssl = { version = "0.10.6" }
oslog = { version = "0.2.0", default-features = false }
p256 = { version = "0.13.2", default-features = false }
proc-macro2 = { version = "1.0.66" }
quote = { version = "1.0.26" }
r2d2-cryptoki = { version = "0.2.1" }
rand = { version = "0.8.5" }
rand_core = { version = "0.6.4" }
rcgen = { version = "0.11.3", default-features = false }
regex = { version = "1.7.0" }
reqwest = { version = "0.11.18", default-features = false }
ring = { version = "0.17.0" }
rstest = { version = "0.18.1" }
rustls-webpki = { version = "0.101.2" }
sea-orm = { version = "0.12.3", default-features = false }
sea-orm-migration = { version = "0.12.3", default-features = false }
sec1 = { version = "0.7.3" }
serde = { version = "1.0.147", default-features = false }
serde_bytes = { version = "0.11.7" }
serde_json = { version = "1.0.92", default-features = false }
serde_repr = { version = "0.1.16" }
serde_with = { version = "3.0.0" }
serial_test = { version = "2.0.0" }
sha2 = { version = "0.10.6" }
syn = { version = "2.0" }
tempfile = { version = "3.5.0" }
thiserror = { version = "1.0.39" }
tokio = { version = "1.27.0", default-features = false }
tower-http = { version = "0.4.0", default-features = false }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
uniffi = { version = "0.24.1", default-features = false }
url = { version = "2.4.0" }
uuid = { version = "1.4.0" }
wiremock = { version = "0.5.19" }
x509-parser = { version = "0.15.1" }
