[workspace]
members = [
    "flutter_api",
    "flutter_api/flutter_api_macros",
    "mdoc",
    "mdoc/fieldnames",
    "mdoc/fieldnames_derive",
    "mock_relying_party",
    "pid_issuer",
    "platform_support",
    "tests_integration",
    "wallet",
    "wallet/entity",
    "wallet/migration",
    "wallet_ca",
    "wallet_common",
    "wallet_provider",
    "wallet_provider/database_settings",
    "wallet_provider/domain",
    "wallet_provider/migrations",
    "wallet_provider/persistence",
    "wallet_provider/service",
    "wallet_server",
    "wallet_server/migration",
]
exclude = ["flutter_rust_bridge_codegen", "uniffi-bindgen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.73"

[workspace.dependencies]
aes-gcm = "0.10.1"
android_logger = "0.13.1"
anyhow = "1.0.66"
assert_cmd = "2.0.12"
assert_fs = "1.0.13"
askama = "0.12.1"
assert_matches = "1"
async-trait = "0.1.68"
axum = { version = "0.6.19", default-features = false }
axum-extra = "0.8.0"
backtrace = "0.3.67"
base64 = "0.21.0"
chrono = { version = "0.4.26", default-features = false }
ciborium = "0.2.1"
clap = "4.4.7"
clio = "0.3.4"
config = { version = "0.13.3", default-features = false }
coset = "0.3.3"
cryptoki = "0.6.0"
cstr = "0.2.11"
ctor = "0.2.5"
dashmap = "5.4.0"
der = "0.7.7"
dotenvy = "0.15.7"
flutter_rust_bridge = "1.70.0"
futures = "0.3.17"
hex = "0.4.3"
hex-literal = "0.4.1"
http = "0.2.9"
hmac = "0.12.1"
indexmap = "2.0.2"
itertools = "0.11.0"
jni = "0.21.1"
josekit = "0.8.3"
jsonwebtoken = "8.2.0"
lazy_static = "1.4.0"
libsqlite3-sys = { version = "0.26.0", default-features = false }
mime = "0.3.17"
mockall = "0.11.4"
never = "0.1.0"
once_cell = "1.17.1"
openid = { version = "0.12.0", default-features = false }
openssl = "0.10.6"
oslog = { version = "0.2.0", default-features = false }
p256 = { version = "0.13.2", default-features = false }
pem = "3.0.2"
predicates = "3.0.4"
proc-macro2 = "1.0.66"
quote = "1.0.26"
r2d2-cryptoki = "0.2.1"
rand = "0.8.5"
rand_core = "0.6.4"
rcgen = { version = "0.11.3", default-features = false }
regex = "1.7.0"
reqwest = { version = "0.11.18", default-features = false }
ring = "0.17.0"
rstest = "0.18.1"
rustls-webpki = "0.101.2"
sea-orm = { version = "0.12.3", default-features = false }
sea-orm-migration = { version = "0.12.3", default-features = false }
sec1 = "0.7.3"
serde = { version = "1.0.147", default-features = false }
serde_bytes = "0.11.7"
serde_json = { version = "1.0.92", default-features = false }
serde_repr = "0.1.16"
serde_urlencoded = "0.7.1"
serde_with = "3.3.0"
serial_test = "2.0.0"
sha2 = "0.10.6"
syn = "2.0"
tempfile = "3.5.0"
thiserror = "1.0.39"
tokio = { version = "1.27.0", default-features = false }
tower-http = { version = "0.4.0", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
uniffi = { version = "0.24.1", default-features = false }
url = "2.4.0"
uuid = "1.4.0"
wiremock = "0.5.19"
x509-parser = "0.15.1"

[patch.crates-io]
cryptoki = { git = "https://github.com/reduced-permissions-bot/rust-cryptoki.git" }
r2d2-cryptoki = { git = "https://github.com/reduced-permissions-bot/r2d2-cryptoki" }
