[workspace]
members = [
    "flutter_api",
    "mdoc",
    "mdoc/fieldnames",
    "mdoc/fieldnames_derive",
    "platform_support",
    "wallet",
    "wallet_common",
    "wallet_provider",
    "pid_issuer",
]
exclude = ["flutter_rust_bridge_codegen", "uniffi-bindgen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

[workspace.dependencies]
aes-gcm = "0.10.1"
android_logger = "0.13.1"
anyhow = "1.0.66"
assert_matches = "1"
async-trait = "0.1.68"
axum = { version = "0.6.19", default-features = false }
backtrace = "0.3.67"
base64 = "0.21.0"
chrono = { version = "0.4.26", default-features = false }
ciborium = { version = "0.2.1" }
config = { version = "0.13.3", default-features = false }
coset = { version = "0.3.3" }
cstr = "0.2.11"
dashmap = { version = "5.4.0" }
der = "0.7.7"
flutter_rust_bridge = "1.70.0"
hex = { version = "0.4.3" }
hex-literal = { version = "0.3.4" }
http = "0.2.9"
indexmap = { version = "1.9.2" }
jni = "0.21.1"
josekit = "0.8.3"
jsonwebtoken = "8.2.0"
libsqlite3-sys = { version = "0.24.2", default-features = false }
mime = { version = "0.3.17" }
never = "0.1.0"
once_cell = "1.17.1"
openid = "0.12.0"
oslog = { version = "0.2.0", default-features = false }
p256 = { version = "0.13.2", default-features = false }
pkce = "0.2.0"
quote = "1.0.26"
rand = "0.8.5"
rand_core = "0.6.4"
rcgen = { version = "0.10.0", default-features = false }
regex = { version = "1.7.0" }
reqwest = { version = "0.11.16", default-features = false }
ring = "0.16.20"
rstest = "0.18.1"
rustls-webpki = { version = "0.101.2" }
sea-orm = { version = "0.11.3", default-features = false }
sea-orm-migration = { version = "0.11.0", default-features = false }
serde = { version = "1.0.147", default-features = false }
serde_bytes = { version = "0.11.7" }
serde_json = { version = "1.0.92", default-features = false }
serde_with = { version = "3.0.0" }
serial_test = "2.0.0"
sha2 = "0.10.6"
syn = "2.0"
tempfile = "3.5.0"
thiserror = "1.0.39"
tokio = { version = "1.27.0", default-features = false }
tower-http = { version = "0.4.0", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
typetag = { version = "0.2.8" }
uniffi = { version = "0.24.1", default-features = false }
url = "2.4.0"
uuid = "1.4.0"
wiremock = "0.5.19"
x509-parser = { version = "0.14.0" }
