[workspace]
members = [
    "flutter_api",
    "platform_support",
    "wallet",
    "wallet_common",
    "wallet_provider",
]
exclude = ["flutter_rust_bridge_codegen", "uniffi-bindgen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

[workspace.dependencies]
aes-gcm = "0.10.1"
android_logger = "0.13.1"
anyhow = "1.0.66"
async-trait = "0.1.68"
axum = { version = "0.6.12", default-features = false }
backtrace = "0.3.67"
base64 = "0.21.0"
config = { version = "0.13.3", default-features = false }
cstr = "0.2.11"
der = "0.7.7"
flutter_rust_bridge = "1.70.0"
futures = { version = "0.3.28", default-features = false }
http = "0.2.9"
jni = "0.21.1"
jsonwebtoken = "8.2.0"
libsqlite3-sys = { version = "0.24.2", default-features = false }
never = "0.1.0"
mime = "0.3.17"
once_cell = "1.17.1"
oslog = { version = "0.2.0", default-features = false }
p256 = { version = "0.13.2", default-features = false }
quote = "1.0.26"
rand = "0.8.5"
rand_core = "0.6.4"
reqwest = { version = "0.11.16", default-features = false }
ring = "0.16.20"
sea-orm = { version = "0.11.3", default-features = false }
sea-orm-migration = { version = "0.11.0", default-features = false }
serde = { version = "1.0.147", default-features = false }
serde_json = { version = "1.0.92", default-features = false }
serial_test = "2.0.0"
sha2 = "0.10.6"
syn = "2.0"
tempfile = "3.5.0"
thiserror = "1.0.39"
tokio = { version = "1.27.0", default-features = false }
tower-http = { version = "0.4.0", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
uniffi = { version = "0.24.1", default-features = false }
url = "2.4.0"
uuid.version = "1.4.0"
wiremock = "0.5.19"
