stages:
  - test
  - build
  - deploy

analyze-app:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-flutter@sha256:a4ee5bd0eaeb3511548790cdf752a28373579c13a755091d27077da7e81c50f1"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter analyze
    
test-flutter:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-flutter@sha256:a4ee5bd0eaeb3511548790cdf752a28373579c13a755091d27077da7e81c50f1"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter test --exclude-tags=golden

test-flutter-ui:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  when: manual
  tags:
    - macos
  artifacts:
    name: "ui-test-failures"
    when: on_failure
    paths:
      - "**/failures/*.png"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter test --tags=golden

test-rust:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-rust@sha256:7fb5da3cef6ea249f52f437f201d9f4bd181b724360420550fd4a3cc4c0a0d9f"
  script:
    - set -euxo pipefail
    - cargo test --manifest-path rust_core/Cargo.toml --features software,integration-test

test-ios:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  when: manual
  tags:
    - macos
  artifacts:
    name: "test_output"
    when: on_failure
    paths:
      - "fastlane/test_output/*"
  variables:
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane disable_flutter_analytics
    - bundle exec fastlane ios test

test-rust-fmt:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-rust@sha256:7fb5da3cef6ea249f52f437f201d9f4bd181b724360420550fd4a3cc4c0a0d9f"
  script:
    - set -euxo pipefail
    - find rust_core -mindepth 2 -type f -name Cargo.toml -print0 | xargs -0 -n1 cargo fmt --manifest-path
    - git diff --stat
    - if [ $(git diff --shortstat | wc -l) -gt 0 ]; then echo "Rust formatting results in different files!"; exit 1; fi

test-codegen:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-flutter-rust@sha256:72e92321ab70fd23910efa74677e5d087933430ac314f9aca42bc1f055b17340"
  script:
    - set -euxo pipefail
    - flutter pub get
    - cargo run --manifest-path rust_core/flutter_rust_bridge_codegen/Cargo.toml
    - cargo run --manifest-path rust_core/Cargo.toml --bin serde_reflection_codegen --features serde_reflection_codegen
    - git diff --stat
    - if [ $(git diff --shortstat | wc -l) -gt 0 ]; then echo "Code generation results in different files!"; exit 1; fi

build-android-app:
  stage: build
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-android-flutter-rust@sha256:d33dde486a0876fb91a8ad3e57e2edf8285855a750fa66ece4f4c0dc609d71af"
  artifacts:
    name: "wallet-android"
    paths:
      - "*.aab"
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane disable_flutter_analytics
    - bundle exec fastlane android ci_build

deploy-android-app:
  stage: deploy
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-fastlane@sha256:436af2468f17e6723b99d61a402ad2e5d1af46631455a247129468147670c487"
  needs:
    - build-android-app
  dependencies:
    - build-android-app
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane android ci_deploy

build-ios-app:
  stage: build
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  when: manual
  tags:
    - macos
  artifacts:
    name: "wallet-ios"
    paths:
      - "*.ipa"
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane disable_flutter_analytics
    - bundle exec fastlane ios ci_build

deploy-ios-app:
  stage: deploy
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  needs:
    - build-ios-app
  dependencies:
    - build-ios-app
  tags:
    - macos
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane disable_flutter_analytics
    - bundle exec fastlane ios ci_deploy
