stages:
  - analyze
  - test
  - build

analyze-app:
  stage: analyze
  only:
    refs:
      - merge_requests
      - main
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-flutter@sha256:9d378696afdfd3d5d35b73d644de6abbf9871fe2d0d69cc44d5ba84c6d5f1c52"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter analyze

test-app:
  stage: test
  only:
    refs:
      - merge_requests
      - main
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-flutter@sha256:9d378696afdfd3d5d35b73d644de6abbf9871fe2d0d69cc44d5ba84c6d5f1c52"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter test

# TODO: Use fastlane for building
build-app:
  stage: build
  only:
    refs:
      - main
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-android-flutter@sha256:14a22d8126603be0b1930ddd536f2c094040711c0f44d57c2536bd994a295a1e"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter pub get
    - flutter build apk
  artifacts:
    paths:
      - "build/app/outputs/apk/release/app-release.apk"
