stages:
  - test
  - build
  - deploy

analyze-app:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-flutter@sha256:a4ee5bd0eaeb3511548790cdf752a28373579c13a755091d27077da7e81c50f1"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter analyze
    
test-flutter:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-flutter@sha256:a4ee5bd0eaeb3511548790cdf752a28373579c13a755091d27077da7e81c50f1"
  script:
    - set -euxo pipefail
    - flutter --version
    - flutter test

test-rust:
  stage: test
  only:
    - merge_requests
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-rust@sha256:7fb5da3cef6ea249f52f437f201d9f4bd181b724360420550fd4a3cc4c0a0d9f"
  script:
    - set -euxo pipefail
    - cd rust_core
    - cargo test

build-android-app:
  stage: build
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-android-flutter-rust@sha256:d33dde486a0876fb91a8ad3e57e2edf8285855a750fa66ece4f4c0dc609d71af"
  artifacts:
    name: "wallet-android"
    paths:
      - "*.aab"
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane disable_flutter_analytics
    - bundle exec fastlane android ci_build

deploy-android-app:
  stage: deploy
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-fastlane@sha256:436af2468f17e6723b99d61a402ad2e5d1af46631455a247129468147670c487"
  needs:
    - build-android-app
  dependencies:
    - build-android-app
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane android ci_deploy

build-ios-app:
  stage: build
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  when: manual
  tags:
    - macos
  artifacts:
    name: "wallet-ios"
    paths:
      - "*.ipa"
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane disable_flutter_analytics
    - bundle exec fastlane ios ci_build

deploy-ios-app:
  stage: deploy
  only:
    - main
    - /^(alpha|beta|release)\/\d+\.\d+\.\d+$/
  needs:
    - build-ios-app
  dependencies:
    - build-ios-app
  tags:
    - macos
  environment:
    name: ${K8S_CLUSTER}
    kubernetes:
      namespace: ${K8S_NAMESPACE}
  variables:
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - bundle install
    - bundle exec fastlane disable_flutter_analytics
    - bundle exec fastlane ios ci_deploy
