version: '3.9'

services:
  postgresql:
    image: docker.io/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./scripts/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      wallet_provider_network:
        ipv4_address: 172.20.20.2

  pgadmin4:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@wallet.com"
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "9090:80"
    depends_on:
      - postgresql
    networks:
      wallet_provider_network:
        ipv4_address: 172.20.20.3

volumes:
  postgresql_data:
    driver: local

networks:
  wallet_provider_network:
    ipam:
      config:
        - subnet: 172.20.20.0/24
