[package]
name = "tests_integration_common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ctor.workspace = true
indexmap.workspace = true
jsonwebtoken.workspace = true
reqwest = { workspace = true, features = ["rustls-tls-webpki-roots"] }
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
    "debug-print",
] }
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

configuration_server = { path = "../../configuration_server" }
nl_wallet_mdoc = { path = "../../mdoc", features = [
    "generate",
    "software_key_factory",
    "test",
    "mock",
] } # Enable the features necessary to run all integration tests
openid4vc = { path = "../../openid4vc" }
platform_support = { path = "../../platform_support", features = ["software"] }
wallet = { path = "../../wallet", features = [
    "mock",
    "wallet_deps",
    "env_config",
] }
wallet_common.path = "../../wallet_common"
wallet_provider = { path = "../../wallet_provider" }
wallet_provider_persistence = { path = "../../wallet_provider/persistence" }
wallet_server = { path = "../../wallet_server", features = [
    "issuance",
    "mock",
] }
