[package]
name = "tests_integration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[test]]
name = "config_server"
path = "tests/config_server.rs"
required-features = ["db_test", "hsm_test"]

[[test]]
name = "disclosure"
path = "tests/disclosure.rs"
required-features = ["db_test", "hsm_test"]

[[test]]
name = "issuance"
path = "tests/issuance.rs"
required-features = ["db_test", "hsm_test"]

[[test]]
name = "locking"
path = "tests/locking.rs"
required-features = ["db_test", "hsm_test"]

[[test]]
name = "registration"
path = "tests/registration.rs"
required-features = ["db_test", "hsm_test"]

[features]
# Allow the disclosure return URL and its prefix to use http://
allow_http_return_url = ["nl_wallet_mdoc/allow_http_return_url"]
# Include and run test that depend on an external PostgreSQL database
db_test = ["allow_http_return_url"]
hsm_test = []
digid_test = []

[dependencies]

[dev-dependencies]
assert_matches.workspace = true
indexmap.workspace = true
jsonwebtoken.workspace = true
p256 = { workspace = true, features = ["pkcs8"] }
rand_core.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["rustls-tls-webpki-roots"] }
rstest.workspace = true
serial_test.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "sync", "parking_lot"] }
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

nl_wallet_mdoc = { path = "../mdoc", features = [
    "generate",
    "software_key_factory",
    "test",
    "mock",
] } # Enable the features necessary to run all integration tests
openid4vc = { path = "../openid4vc" }
tests_integration_common = { path = "./common" }
wallet = { path = "../wallet", features = [
    "mock",
    "wallet_deps",
] }
wallet_common.path = "../wallet_common"
wallet_provider_service = { path = "../wallet_provider/service", features = [
    "software_keys",
    "mock",
] } # Enable the features necessary to run all integration tests, minus "db_test" and "hsm_test"
wallet_server = { path = "../wallet_server", features = ["mock"] }
