[package]
name = "flutter_api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "wallet_core"
crate-type = ["staticlib", "cdylib"]

[dependencies]
macros = { path = "macros" }
wallet = { path = "../wallet" }
anyhow.workspace = true
backtrace.workspace = true
flutter_rust_bridge.workspace = true
once_cell.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "parking_lot"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["parking_lot"] }

[target.'cfg(target_os = "android")'.dependencies]
android_logger.workspace = true
cstr.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
oslog = { workspace = true }
