[package]
name = "flutter_api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "wallet_core"
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "serde_reflection_codegen"
required-features = ["serde_reflection_codegen"]

[features]
serde_reflection_codegen = [
    "dep:const_format",
    "dep:serde-generate",
    "dep:serde-reflection",
]

[dependencies]
macros = { path = "macros" }
wallet = { path = "../wallet" }
anyhow = "1.0.69"
backtrace = "0.3.67"
bincode = "1.3.3"
const_format = { version = "0.2.30", optional = true }
flutter_rust_bridge = "1.70.0"
once_cell = "1.17.1"
serde = { version = "1.0.156", features = ["derive"] }
serde-generate = { version = "0.25.0", optional = true }
serde-reflection = { version = "0.3.6", optional = true }
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.1"
cstr = "0.2.11"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = { version = "0.2.0", default-features = false }
