apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nl-wallet-letsencrypt-live-issuer
spec:
  acme:
    email: # Add email to which Let's Encrypt can send info on certificate expiry etc.
    server: https://acme-v02.api.letsencrypt.org/directory # Let's Encrypt ACME server
    privateKeySecretRef:
      name: nl-wallet-letsencrypt-live-issuer-key # Generated and implicitly used by Certmanager/ACME server
    solvers:
      - http01: # https://cert-manager.io/docs/configuration/acme/#creating-a-basic-acme-issuer
          ingress: # Temporary Ingress on which the http01 resolver Pod will be reached
            class: nginx
            podTemplate: # https://cert-manager.io/docs/configuration/acme/http01/#podtemplate
              metadata:
                labels:
                  ingress-controller-frontoffice-policy: allow
                  egress-frontoffice-policy: allow
