[package]
name = "hw_keystore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
p256 = { version = "0.12.0", optional = true }
rand_core = { version = "0.6.4", optional = true }

[features]
software = ["dep:p256", "dep:rand_core"]
