apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-cluster-pi
spec:
  resources:
    requests:
      memory: "128Mi"
      cpu: "0.2"
    limits:
      memory: "128Mi"
      cpu: "0.2"
  storage:
    size: 10Gi
  walStorage:
    size: 10Gi

  postgresql:
    parameters:
      shared_buffers: "128MB"
