[package]
name = "flutter_api_macros"
description = "Support macros for flutter_api."
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true
doctest = false

[dependencies]
quote.workspace = true
syn = { workspace = true, features = ["full"] }
