[package]
name = "wallet_provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "wallet_provider"

[[bin]]
name = "wallet_provider_migrations"
required-features = ["wallet_provider_migrations"]

[features]
wallet_provider_migrations = ["dep:sea-orm-migration"]
db_test = []
live_test = []

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = [
    "http1",
    "json",
    "tokio",
    "tower-log",
    "tracing",
] }
base64 = { workspace = true }
chrono = { workspace = true, features = ["std", "clock"] }
config = { workspace = true, features = ["toml"] }
http = { workspace = true }
mime = { workspace = true }
once_cell = { workspace = true, features = ["parking_lot"] }
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
sea-orm-migration = { workspace = true, features = ["cli"], optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "parking_lot",
    "macros",
] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "parking_lot",
    "json",
] }
uuid = { workspace = true, features = ["serde", "v4"] }

wallet_provider_domain = { path = "domain" }
wallet_provider_migration = { path = "migration" }
wallet_provider_persistence = { path = "persistence" }
wallet_provider_service = { path = "service" }
wallet_common = { path = "../wallet_common" }

[dev-dependencies]
assert_matches = { workspace = true }
reqwest = { workspace = true, features = ["rustls-tls-webpki-roots"] }
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
] }
serial_test = { workspace = true }
url = { workspace = true }

nl_wallet_mdoc = { path = "../mdoc" }
pid_issuer = { path = "../pid_issuer", features = ["mock"] }
platform_support = { path = "../platform_support", features = ["software"] }
wallet = { path = "../wallet", features = ["mock", "wallet_deps"] }
