[package]
name = "wallet_provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "wallet_provider"

[features]
db_test = []

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = [
    "http1",
    "json",
    "tokio",
    "tower-log",
    "tracing",
] }
base64 = { workspace = true }
chrono = { workspace = true, features = ["clock", "serde", "std"] }
config = { workspace = true, features = ["toml"] }
http = { workspace = true }
mime = { workspace = true }
once_cell = { workspace = true, features = ["parking_lot"] }
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["chrono_0_4"] }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "parking_lot",
    "macros",
] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "parking_lot",
    "json",
] }
uuid = { workspace = true, features = ["serde", "v4"] }

wallet_provider_database_settings = { path = "database_settings" }
wallet_provider_domain = { path = "domain" }
wallet_provider_persistence = { path = "persistence" }
wallet_provider_service = { path = "service" }
wallet_common = { path = "../wallet_common" }
