[package]
name = "wallet_provider"
version.workspace = true
edition.workspace = true

[lib]

[[bin]]
name = "wallet_provider"

[features]
stub = []

[dependencies]
wallet_common = { path = "../wallet_common" }
anyhow = "1.0.66"
axum = { version = "0.6.12" }
base64 = "0.21.0"
config = "0.13.3"
der = { version = "0.6.1", features = ["alloc"] }
jsonwebtoken = "8.2.0"
p256 = { version = "0.12.0", features = ["pem"] }
rand = "0.8.5"
serde = { version = "1.0.147", features = ["serde_derive"] }
sha2 = "0.10.6"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
wallet_common = { path = "../wallet_common", features = ["mock"] }
