[package]
name = "wallet_provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[[bin]]
name = "wallet_provider"

[[bin]]
name = "wallet_provider_migrations"
required-features = ["wallet_provider_migrations"]

[features]
stub = ["wallet_provider_service/stub"]
wallet_provider_migrations = ["dep:sea-orm-migration"]
db_test = []

[dependencies]
wallet_provider_domain = { path = "domain" }
wallet_provider_migration = { path = "migration" }
wallet_provider_persistence = { path = "persistence" }
wallet_provider_service = { path = "service" }
wallet_common = { path = "../wallet_common" }

async-trait.workspace = true
axum = { workspace = true, features = [
    "http1",
    "json",
    "tokio",
    "tower-log",
    "tracing",
] }
base64.workspace = true
config = { workspace = true, features = ["toml"] }
p256.workspace = true
sea-orm-migration = { workspace = true, features = ["cli"], optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "parking_lot",
    "macros",
] }
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "parking_lot",
] }
uuid = { workspace = true, features = ["serde", "v4"] }

[dev-dependencies]
platform_support = { path = "../platform_support", features = ["software"] }
wallet = { path = "../wallet", features = ["mock"] }
sea-orm = { workspace = true, features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
] }

axum-test-helper.workspace = true
url.workspace = true
once_cell.workspace = true
serial_test.workspace = true
