[package]
name = "wallet_provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[[bin]]
name = "wallet_provider"

[features]
stub = []

[dependencies]
wallet_common = { path = "../wallet_common" }
axum = { workspace = true }
base64.workspace = true
config.workspace = true
der = { workspace = true, features = ["alloc"] }
jsonwebtoken.workspace = true
p256 = { workspace = true, features = ["pem"] }
pkcs8 = { workspace = true, features = ["std"] }
rand.workspace = true
serde = { workspace = true, features = ["serde_derive"] }
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "parking_lot", "macros"] }
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "parking_lot"] }

[dev-dependencies]
platform_support = { path = "../platform_support", features = ["software"] }
wallet = { path = "../wallet", features = ["mock"] }
wallet_common = { path = "../wallet_common", features = ["mock"] }
# stub feature is required for integration tests
wallet_provider = { path = "../wallet_provider", features = ["stub"] }
anyhow.workspace = true
async-trait.workspace = true
axum-test-helper.workspace = true
