# The commented out lines show optional configuration with their default value.
# All key material should be replaced with secret values.

# Identifier for key used to sign JWT's sent from wallet_provider to wallet
certificate_signing_key_identifier = "certificate_signing_key"

# Identifier for key used to sign instruction results sent from wallet_provider to wallet
instruction_result_signing_key_identifier = "instruction_result_signing_key"

# Identifier for key used to wrap attestation private keys that will be persisted
attestation_wrapping_key_identifier = "attestation_wrapping_key"

# Identifier for key used to encrypt the pin public key
pin_pubkey_encryption_key_identifier = "pin_pubkey_encryption_key"

# Identifier for key used to sign the hash of the pin public key for use in the wallet certificate
pin_public_disclosure_protection_key_identifier = "pin_public_disclosure_protection_key"

# Identifier for key used to issue WTEs to wallets
wte_signing_key_identifier = "wte_signing_key"

# Identifier for the WTE issuer. Must equal the CN from the WTE trust anchor CA certificate.
wte_issuer_identifier = "wte-issuer.example.com"

# Indicates whether logging should be output in a structured (JSON) manner.
#structured_logging = false

[database]
# host = "localhost"
# username = "postgres"
# password = "postgres"
# name = "wallet_provider"

[webserver]
# ip = "0.0.0.0"
# port = 3000

[pin_policy]
# rounds = 4
# attempts_per_round = 4
# timeouts_in_ms = [60_000, 300_000, 3_600_000]

[hsm]
library_path = "/usr/lib/softhsm/libsofthsm2.so"
user_pin = "12345678"

[ios]
team_identifier = "123ABC321A"
bundle_identifier = "com.example.wallet-app"
# The "environment" can be either "development" or "production", the latter being the default.
# environment = production
