# The commented out lines show optional configuration with their default value.
# All key material should be replaced with secret values.

# Identifier for key used to sign JWT's sent from wallet_provider to wallet
certificate_signing_key_identifier = "certificate_signing_key"

# Identifier for key used to sign instruction results sent from wallet_provider to wallet
instruction_result_signing_key_identifier = "instruction_result_signing_key"



# Indicates whether logging should be output in a structured (JSON) manner.
#structured_logging = false

[database]
# host = "localhost"
# username = "postgres"
# password = "postgres"
# name = "wallet_provider"

[webserver]
# ip = "0.0.0.0"
# port = 3000

[pin_policy]
# rounds = 4
# attempts_per_round = 4
# timeouts_in_ms = [60_000, 300_000, 3_600_000]

[hsm]
library_path = "/usr/lib/softhsm/libsofthsm2.so"
user_pin = "12345678"
