[package]
name = "nl_wallet_mdoc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mock = []

[dependencies]
fieldnames = { path = "./fieldnames" }
fieldnames_derive = { path = "./fieldnames_derive" }

async-trait = { workspace = true }
chrono = { workspace = true }
ciborium = { workspace = true }
coset = { workspace = true, features = ["std"] }
dashmap = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
indexmap = { workspace = true , features = ["serde"] }
once_cell = { workspace = true }
p256 = { workspace = true , features = ["ecdh", "ecdsa", "pem", "serde", "std"] }
rand = { workspace = true }
rcgen = { workspace = true , features = ["x509-parser"] }
regex = { workspace = true }
ring = { workspace = true }
rustls-webpki = { workspace = true }
serde = { workspace = true , features = ["serde_derive"] }
serde_bytes = { workspace = true, features = ["std"] }
serde_with = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true , features = ["macros", "rt"] }
typetag = { workspace = true }
x509-parser = { workspace = true , features = ["verify", "validate"] }

wallet_common = { path = "../wallet_common" }

[dev-dependencies]
anyhow = "1.0.66"
nl_wallet_mdoc = { path = ".", features = ["mock"] }

[lib]
