[package]
name = "nl-wallet-mdoc"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mock = []

[dependencies]
async-trait = "0.1.68"
chrono = "0.4.26"
ciborium = "0.2.1"
coset = "0.3.3"
dashmap = "5.4.0"
fieldnames = {path = "./fieldnames" }
fieldnames_derive = {path = "./fieldnames_derive" }
hex = "0.4.3"
hex-literal = "0.3.4"
indexmap = { version = "1.9.2", features = ["serde"] }
once_cell = "1.17.1"
p256 = { version = "0.13.2", features = ["ecdh", "serde", "pem"] }
rand = "0.8.5"
rcgen = { version = "0.10.0", features = ["x509-parser"] }
regex = "1.7.0"
ring = "0.16.20"
rustls-webpki = { git = "https://github.com/rustls/webpki", rev = "d96f6f5" }
serde = { version = "1.0.147", features = ["serde_derive"] }
serde_bytes = "0.11.7"
serde_with = "3.0.0"
sha2 = "0.10.6"
thiserror = "1.0.39"
tokio = { version = "1.27.0", features = ["macros", "rt"] }
typetag = "0.2.8"
x509-parser = { version = "0.14.0", features = ["verify", "validate"] }

[dev-dependencies]
anyhow = "1.0.66"
nl-wallet-mdoc = { path = ".", features = ["mock"] }

[lib]
