# The commented out lines show optional configuration with their default value.
# All key material should be replaced with secret values.

public_url = "http://${DIGID_CONNECTOR_HOST}:3003/"

[webserver]
# ip = "0.0.0.0"
# port = 3003

[issuer_key]
private_key = "${PID_ISSUER_KEY}"
certificate = "${PID_ISSUER_CRT}"

[digid]
client_id = "${WALLET_CLIENT_ID}"
issuer_url = "https://${DIGID_CONNECTOR_HOST}:8006"
bsn_privkey = '${BSN_PRIVKEY}'
