[package]
name = "migration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
async-trait.workspace = true
sea-orm-migration.workspace = true
