[package]
name = "android_attest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
network_test = []

[dependencies]
chrono = { workspace = true, features = ["serde"] }
num-bigint.workspace = true
num-traits.workspace = true
nutype = { workspace = true, features = ["regex", "serde"] }
regex.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_with.workspace = true
thiserror.workspace = true
x509-parser.workspace = true

[dev-dependencies]
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["macros"] }
wiremock.workspace = true
