[package]
name = "android_attest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
encode = []
mock = ["dep:derive_more", "dep:rcgen"]
network_test = []

[dependencies]
bitflags.workspace = true
chrono = { workspace = true, features = ["serde"] }
const-decoder.workspace = true
http-cache-reqwest = { workspace = true, features = ["manager-moka"] }
int-enum.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
nutype = { workspace = true, features = ["regex", "serde"] }
p256 = { workspace = true, features = ["std", "ecdsa", "pkcs8"] }
rasn = { workspace = true, features = ["std"] }
regex.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
reqwest-middleware.workspace = true
rsa = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["chrono", "hex"] }
spki = { workspace = true, features = ["std"] }
thiserror.workspace = true
url.workspace = true
x509-parser.workspace = true

derive_more = { workspace = true, optional = true, features = ["debug"] }
rcgen = { workspace = true, optional = true, features = ["aws_lc_rs"] }

[dev-dependencies]
assert_matches.workspace = true
p256 = { workspace = true, features = ["pem"] }
rand.workspace = true
rstest.workspace = true
rustls-pki-types.workspace = true
rustls-webpki.workspace = true
tokio = { workspace = true, features = ["macros"] }
wiremock.workspace = true
