[package]
name = "entity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
sea-orm = { workspace = true, features = ["macros", "with-json", "with-uuid", "with-chrono"] }
uuid.workspace = true
