[package]
name = "entity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
sea-orm = { workspace = true, features = ["macros", "with-json", "with-uuid"] }
uuid.workspace = true
