[package]
name = "wallet_provider_persistence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
mock = ["mockall"]
db_test = []

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true, features = ["std", "clock"] }
mockall = { workspace = true, optional = true }
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
sea-orm = { workspace = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "with-chrono",
    "with-uuid",
] }
tokio = { workspace = true, features = ["parking_lot", "rt"] }
tracing = { workspace = true }
uuid = { workspace = true }

wallet_provider_domain = { path = "../domain" }
wallet_common = { path = "../../wallet_common" }

[dev-dependencies]
ctor = { workspace = true }
sea-orm = { workspace = true, features = [
    "debug-print",
    "runtime-tokio-rustls",
    "sqlx-postgres",
] }
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "parking_lot",
] }

wallet_provider_domain = { path = "../domain", features = ["mock"] }
