[package]
name = "wallet_provider_persistence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[test]]
name = "wallet_user"
path = "tests/wallet_user.rs"
required-features = ["db_test"]

[[test]]
name = "wallet_user_keys"
path = "tests/wallet_user_key.rs"
required-features = ["db_test"]

[features]
# Include mock implementations and constructors for testing
mock = ["mockall"]
# Include and run test that depend on an external PostgreSQL database
db_test = []

[dependencies]
chrono = { workspace = true, features = ["std", "clock"] }
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
sea-orm = { workspace = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "with-chrono",
    "with-uuid",
] }
tokio = { workspace = true, features = ["parking_lot", "rt"] }
tracing.workspace = true
uuid.workspace = true

mockall = { workspace = true, optional = true }

wallet_provider_database_settings.path = "../database_settings"
wallet_provider_domain.path = "../domain"
wallet_common.path = "../../wallet_common"

[dev-dependencies]
ctor.workspace = true
sea-orm = { workspace = true, features = [
    "debug-print",
    "runtime-tokio-rustls",
    "sqlx-postgres",
] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros"] }
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "parking_lot",
] }

wallet_provider_domain = { path = "../domain", features = ["mock"] }
