[package]
name = "mock_relying_party"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[features]
# Allow the disclosure return URL and its prefix to use http://
allow_http_return_url = ["wallet_server/allow_http_return_url"]

[dependencies]
anyhow.workspace = true
askama.workspace = true
axum = { workspace = true, features = ["http1", "query", "tokio", "tower-log", "tracing"] }
base64.workspace = true
config = { workspace = true, features = ["toml"] }
futures = { workspace = true, features = ["std"] }
http.workspace = true
memory-serve.workspace = true
nutype = { workspace = true, features = ["serde"] }
once_cell.workspace = true
reqwest = { workspace = true, features = ["rustls-tls-webpki-roots"] }
sentry = { workspace = true, features = [
    "backtrace",
    "contexts",
    "debug-images",
    "panic",
    "anyhow",
    "reqwest",
    "rustls",
    "tracing",
    "log",
] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_urlencoded.workspace = true
strum = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["parking_lot", "rt-multi-thread", "net"] }
tower-http = { workspace = true, features = ["trace", "fs"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = [
    "std",
    "env-filter",
    "fmt",
    "json",
    "ansi",
    "tracing-log",
    "parking_lot"
] }
url = { workspace = true, features = ["serde"] }

nl_wallet_mdoc.path = "../mdoc"
wallet_common = { path = "../wallet_common", features = ["sentry"] }
wallet_server = { path = "../wallet_server", features = ["disclosure"] }
