[package]
name = "openid4vc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
chrono = { workspace = true, features = ["std", "clock"] }
futures.workspace = true
indexmap.workspace = true
itertools.workspace = true
jsonwebtoken.workspace = true
mime.workspace = true
p256 = { workspace = true, features = ["ecdsa", "pem", "serde", "std"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["serde_derive"] }
serde_json.workspace = true
serde_urlencoded.workspace = true
serde_with = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true }
trait-variant.workspace = true
url = { workspace = true, features = ["serde"] }

wallet_common.path = "../wallet_common"
nl_wallet_mdoc.path = "../mdoc"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
rstest.workspace = true
