[package]
name = "openid4vc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[test]]
name = "issuance"
path = "tests/issuance.rs"
required-features = ["integration"]

[[test]]
name = "disclosure"
path = "tests/disclosure.rs"
required-features = ["mock"]

[features]
# Include mock implementations for testing
mock = ["dep:mockall"]
# All features needed to run the integration test
integration = ["mock", "dep:ciborium"]

[dependencies]
base64.workspace = true
biscuit.workspace = true
chrono = { workspace = true, features = ["std", "clock"] }
ciborium = { workspace = true, optional = true }
derive_more.workspace = true
futures.workspace = true
indexmap.workspace = true
itertools.workspace = true
josekit.workspace = true
jsonwebtoken.workspace = true
mime.workspace = true
mockall = { workspace = true, optional = true }
nutype = { workspace = true, features = ["serde"] }
p256 = { workspace = true, features = ["ecdsa", "pem", "serde", "std"] }
regex.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["serde_derive"] }
serde_json.workspace = true
serde_urlencoded.workspace = true
serde_with = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true }
trait-variant.workspace = true
url = { workspace = true, features = ["serde"] }
x509-parser.workspace = true

wallet_common.path = "../wallet_common"
nl_wallet_mdoc.path = "../mdoc"

[dev-dependencies]
assert_matches.workspace = true
mockall.workspace = true
rstest.workspace = true
serde_bytes = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros"] }
wiremock.workspace = true

nl_wallet_mdoc = { path = "../mdoc", features = ["mock", "software_key_factory", "generate", "test"] }
