[package]
name = "openid4vc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[test]]
name = "test"
path = "tests/issuance.rs"

[features]
# Include mock implementations for testing
mock = ["dep:mockall"]

[dependencies]
base64.workspace = true
chrono = { workspace = true, features = ["std", "clock"] }
futures.workspace = true
indexmap.workspace = true
itertools.workspace = true
jsonwebtoken.workspace = true
mime.workspace = true
mockall = { workspace = true, optional = true }
p256 = { workspace = true, features = ["ecdsa", "pem", "serde", "std"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["serde_derive"] }
serde_json.workspace = true
serde_urlencoded.workspace = true
serde_with = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true }
trait-variant.workspace = true
url = { workspace = true, features = ["serde"] }

wallet_common.path = "../wallet_common"
nl_wallet_mdoc.path = "../mdoc"

[dev-dependencies]
ciborium.workspace = true
tokio = { workspace = true, features = ["macros"] }
rstest.workspace = true
nl_wallet_mdoc = { path = "../mdoc", features = ["mock", "software_key_factory", "generate"]}
mockall.workspace = true
