[package]
name = "openid4vc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
chrono = { workspace = true, features = ["std", "clock"] }
futures.workspace = true
jsonwebtoken.workspace = true
p256 = { workspace = true, features = ["ecdh", "ecdsa", "pem", "serde", "std"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["serde_derive"] }
serde_bytes = { workspace = true, features = ["std"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["chrono"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "time", "parking_lot"] }
url = { workspace = true, features = ["serde"] }

serde_urlencoded = "0.7" # TODO move

wallet_common.path = "../wallet_common"
nl_wallet_mdoc.path = "../mdoc"

[dev-dependencies]
assert_matches.workspace = true
mockall.workspace = true
tokio = { workspace = true, features = ["macros"] }
rstest.workspace = true
