apiVersion: v1
kind: Service
metadata:
  name: gba-hc-converter
spec:
  selector:
    app: gba-hc-converter
    tier: vertrouwd
  ports:
    - name: "gba-hc-converter-http"
      port: 3006
      targetPort: 3006
