apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nl-mock-relying-party-public
  labels:
    odcn.rijksapps.nl/inet-loadbalancer: ""
  annotations:
    odcn.rijksapps.nl/inet-loadbalancer-hostnames: "$MOCK_RELYING_PARTY_EXTERNAL_HOSTNAME"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: $MOCK_RELYING_PARTY_EXTERNAL_HOSTNAME
      http:
        paths:
          - backend:
              service:
                name: mock-relying-party
                port:
                  number: 3004
            path: /$MOCK_RELYING_PARTY_EXTERNAL_CONTEXT_PATH/(.*)
            pathType: Prefix
  tls:
    - hosts:
        - $MOCK_RELYING_PARTY_EXTERNAL_HOSTNAME
      secretName: nl-wallet-letsencrypt-live-cert
