apiVersion: apps/v1
kind: Deployment
metadata:
  name: pid-issuer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pid-issuer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: pid-issuer
        tier: vertrouwd
        egress-frontoffice-policy: allow
        ingress-controller-frontoffice-policy: allow
    spec:
      imagePullSecrets:
        - name: harbor-puller
      containers:
        - name: pid-issuer
          image: $PID_ISSUER_IMAGE
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "300m"
          ports:
            - containerPort: 3003
          env:
            - name: PID_ISSUER_ISSUER_KEY__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-pid-issuer-secrets
                  key: issuer_privkey
            - name: PID_ISSUER_ISSUER_KEY__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: nl-pid-issuer-secrets
                  key: issuer_cert
            - name: PID_ISSUER_DIGID__BSN_PRIVKEY
              valueFrom:
                secretKeyRef:
                  name: nl-pid-issuer-secrets
                  key: bsn_privkey
            - name: PID_ISSUER_PUBLIC_URL
              value: "https://${PID_ISSUER_EXTERNAL_HOSTNAME}/${PID_ISSUER_EXTERNAL_CONTEXT_PATH}/"