apiVersion: v1
kind: Pod
metadata:
  name: preload-gba-v-data-pod
  labels:
    app: preload-gba-v-data-pod
    tier: zeer-vertrouwd
    egress-frontoffice-policy: allow
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: harbor-puller
  containers:
    - name: preload-gba-v-data-job
      image: $HARBOR_REGISTRY/quay-proxy/curl/curl:latest
      command: ["/bin/sh", "-c", "--"]
      args:
        - while true; do sleep 30; done;
      volumeMounts:
        - mountPath: /data
          name: preloaded-gba-v-data-volume
        - mountPath: /tmp/preload.sh
          name: preload-script-volume
          subPath: preload.sh
        - mountPath: /tmp/bsn_zoeken_template.xml
          name: zoek-xml-volume
          subPath: bsn_zoeken_template.xml
      env:
        - name: GBAV_ADHOC_URL
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: adhoc_url
        - name: GBAV_USERNAME
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: username
        - name: GBAV_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: password
        - name: GBAV_CLIENT_CERT
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: client_cert
        - name: GBAV_CLIENT_CERT_KEY
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: client_cert_key
        - name: GBAV_CA_API_KEY
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: ca_api_key
        - name: GBAV_PROXY_IP
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: proxy_ip
        - name: GBAV_PROXY_PORT
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: proxy_port
        - name: GBAV_PROXY_USERNAME
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: proxy_username
        - name: GBAV_PROXY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: proxy_password
        - name: GBAV_TRUST_ANCHOR
          valueFrom:
            secretKeyRef:
              name: nl-wallet-gba-hc-converter-secrets
              key: trust_anchor
  volumes:
    - name: preloaded-gba-v-data-volume
      persistentVolumeClaim:
        claimName: preloaded-gba-v-data-pvc
    - name: preload-script-volume
      configMap:
        name: nl-wallet-gba-hc-converter-preload-script
        defaultMode: 0550
    - name: zoek-xml-volume
      configMap:
        name: nl-wallet-gba-hc-converter-zoek-xml
