apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-provider
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-provider
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: wallet-provider
        tier: vertrouwd
        egress-frontoffice-policy: allow
        ingress-controller-frontoffice-policy: allow
        db-in-zeer-vertrouwd: allow
        hsm-in-zeer-vertrouwd: allow
    spec:
      imagePullSecrets:
        - name: harbor-puller
      containers:
        - name: wallet-provider
          image: $WALLET_PROVIDER_IMAGE
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "300m"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: wallet-provider-config
          volumeMounts:
            - name: pkcs11-config-volume
              mountPath: /cs_pkcs11_R3.cfg
              subPath: cs_pkcs11_R3.cfg
            - name: wallet-config-volume
              mountPath: /wallet.toml
              subPath: wallet.toml
          env:
            - name: WALLET_PROVIDER_CERTIFICATE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-secret-signing-keys
                  key: certificate_private_key
            - name: WALLET_PROVIDER_INSTRUCTION_RESULT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-secret-signing-keys
                  key: instruction_result_private_key
            - name: WALLET_PROVIDER_PIN_HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-secret-signing-keys
                  key: pin_hash_salt
            - name: WALLET_PROVIDER_DATABASE__NAME
              value: wallet_provider
            - name: WALLET_PROVIDER_DATABASE__HOST
              value: db-cluster-rw
            - name: WALLET_PROVIDER_DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-app
                  key: username
            - name: WALLET_PROVIDER_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-app
                  key: password
            - name: WALLET_PROVIDER_HSM__USER_PIN
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-provider-hsm
                  key: user_pin
            - name: CS_PKCS11_R3_CFG
              value: "/cs_pkcs11_R3.cfg"
      volumes:
        - name: pkcs11-config-volume
          configMap:
            name: nl-wallet-hsm-pkcs11
        - name: wallet-config-volume
          configMap:
            name: nl-wallet-config
