[package]
name = "wallet_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude = ["resources"]

[lints]
workspace = true

[[bin]]
name = "wallet_server_verifier"
required-features = ["disclosure"]

[[bin]]
name = "pid_issuer"
required-features = ["issuance"]

[[bin]]
name = "wallet_server"
required-features = ["disclosure", "issuance"]

[lib]
doctest = false

[[test]]
name = "verifier_api"
path = "tests/verifier_api.rs"
required-features = ["cfg_test"]

[[test]]
name = "postgres"
path = "tests/postgres.rs"
required-features = ["db_test"]

[features]
default = ["postgres"]
# Allow the disclosure return URL and its prefix to use http://
allow_http_return_url = ["nl_wallet_mdoc/allow_http_return_url"]
# Include session storage in PostgreSQL
postgres = [
    "dep:sea-orm",
    "dep:strum",
]
# Include and run test that depend on an external PostgreSQL database
db_test = ["postgres", "cfg_test", "dep:serial_test", "nl_wallet_mdoc/test"]
cfg_test = [
    "dep:assert_matches",
    "dep:indexmap",
    "dep:parking_lot",
    "dep:serde_urlencoded",
    "tokio/test-util",
    "nl_wallet_mdoc/mock_time",
] # Include and run test that depend on a valid configuration file
# Enable issuance
issuance = [
    "axum/form",
    "dep:ciborium",
    "dep:futures",
    "dep:indexmap",
    "dep:reqwest",
    "dep:serde_urlencoded",
    "dep:openid4vc",
]
# Enable disclosure
disclosure = [
    "dep:ring",
]
# Enable mock PID issuance
mock = ["dep:rand", "issuance"]

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["headers", "http1", "json", "query", "tokio", "tower-log", "tracing"] }
base64.workspace = true
cfg-if.workspace = true
chrono = { workspace = true, features = ["clock", "serde", "std"] }
config = { workspace = true, features = ["toml"] }
http.workspace = true
hyper = { version = "0.14.27", features = ["full"] } # TODO do we realy need full here? we onoly use hyper::body::to_bytes(body)
mime.workspace = true
nutype = { workspace = true, features = ["serde"] }
p256 = { workspace = true, features = ["ecdsa"] }
sentry = { workspace = true, features = ["backtrace", "contexts", "debug-images", "panic", "anyhow", "reqwest", "rustls", "tracing", "log"] }
serde = { workspace = true, features = ["serde_derive"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["base64", "hex"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "parking_lot", "rt-multi-thread"] }
tower-http = { workspace = true, features = ["auth", "cors", "trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["parking_lot"] }
url = { workspace = true, features = ["serde"] }

assert_matches = { workspace = true, optional = true }
ciborium = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true, features = ["serde"] }
parking_lot = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true, features = ["rustls-tls-webpki-roots"] }
ring = { workspace = true, optional = true }
sea-orm = { workspace = true, optional = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "with-chrono",
    "with-json",
] }
serde_urlencoded = { workspace = true, optional = true }
serial_test = { workspace = true, optional = true }
strum = { workspace = true, optional = true, features = ["derive"] }

nl_wallet_mdoc.path = "../mdoc"
openid4vc = { path = "../openid4vc", optional = true }
wallet_common = { path = "../wallet_common", features = ["sentry"] }

[dev-dependencies]
rstest.workspace = true
