[package]
name = "wallet_server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = [
    "headers",
    "http1",
    "json",
    "tokio",
    "tower-log",
    "tracing",
] }
base64.workspace = true
chrono.workspace = true
config = { workspace = true, features = ["toml"] }
dashmap = { workspace = true, features = ["serde"] }
lazy_static.workspace = true
mime.workspace = true
p256 = { workspace = true, features = ["ecdsa"] }
reqwest.workspace = true
sea-orm = { workspace = true, optional = true, features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "with-chrono",
    "with-json",
] }
serde = { workspace = true, features = ["serde_derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
    "parking_lot",
] }
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["parking_lot"] }
url = { workspace = true, features = ["serde"] }

nl_wallet_mdoc.path = "../mdoc"
wallet_common.path = "../wallet_common"

[features]
default = []
postgres = ["dep:sea-orm"]

[dev-dependencies]
indexmap.workspace = true
reqwest.workspace = true

nl_wallet_mdoc = { path = "../mdoc", features = ["generate"] }
