# Example config

trust_anchors = []

[wallet_server]
ip = '127.0.0.1'
port = 3001

[requester_server]
ip = '127.0.0.1'
port = 3002

# TODO sync with actual conf file
[issuer_key]
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgRhZpK1rtKwHUEaN+3H6TAW85kbAg05ZPlD28/Avq42OhRANCAAQQ//yIyvGngF6HFQMR6soElG5EJyaSG8udpzoIznA2onR3f4HI0jc0+xkPv+2zoSzEP/zZPDqzYwUZ2OHT2eru"
certificate = "MIIBozCCAUmgAwIBAgIUEJO8I8aqiq16CuKSPw0i+ePQOhswCgYIKoZIzj0EAwIwGTEXMBUGA1UEAwwOY2EuZXhhbXBsZS5jb20wHhcNMjMxMTA4MDkxNTQzWhcNMjUwMzIyMDkxNTQzWjAaMRgwFgYDVQQDDA9waWQuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQQ//yIyvGngF6HFQMR6soElG5EJyaSG8udpzoIznA2onR3f4HI0jc0+xkPv+2zoSzEP/zZPDqzYwUZ2OHT2eruo24wbDALBgNVHQ8EBAMCB4AwEgYDVR0lBAswCQYHKIGMXQUBAjAJBgNVHRMEAjAAMB0GA1UdDgQWBBSAPWwcDjuxRV3Nwv0i/kSGzUivdzAfBgNVHSMEGDAWgBTKJQKV3gh0c5gZsRfNYmyehluwbTAKBggqhkjOPQQDAgNIADBFAiApRyp6+AaFZyxmSW2WN48qUUteNL80T3nUIiWg9gWblAIhANGPX5a8avCdZEd90Qmc7XqaKQv+hdbilKw5hXh3CukC"

[usecases]
[usecases.driving_license]
certificate = "MIIBUTCB96ADAgECAhRl6OcmpjijxCkA1a76/tIvYLtmLDAKBggqhkjOPQQDAjAZMRcwFQYDVQQDDA5jYS5leGFtcGxlLmNvbTAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEwMTAwMDAwMFowGzEZMBcGA1UEAwwQY2VydC5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ/4iuWfQiqAh8PRmfUiM3wj/YMKwLsJ6xTYvT+2rdPW6SXqCOUOcqv7saSirWMKdjzYdfxKqAfSO9SI1Fv8my6jGTAXMBUGA1UdJQEB/wQLMAkGByiBjF0FAQIwCgYIKoZIzj0EAwIDSQAwRgIhAOKwEjS0R06oplVv1BNLNvd0U6cN/IedFLLpRbiIbyLBAiEApVM0esHuTunDjTkStRhlaTA/LFhjYhC+LOpNu5RFXfQ="
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgeWoxq6+7o1oiBXZvSfl91r1DaLWKJHjamWIOEY7aH0WhRANCAASf+Irln0IqgIfD0Zn1IjN8I/2DCsC7CesU2L0/tq3T1ukl6gjlDnKr+7Gkoq1jCnY82HX8SqgH0jvUiNRb/Jsu"

[usecases.parking_permit]
certificate = "MIIBUTCB+KADAgECAhUA11suNYBz8xIKnCjrw0S0aTzCMQIwCgYIKoZIzj0EAwIwGTEXMBUGA1UEAwwOY2EuZXhhbXBsZS5jb20wIBcNNzUwMTAxMDAwMDAwWhgPNDA5NjAxMDEwMDAwMDBaMBsxGTAXBgNVBAMMEGNlcnQuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQYYLYHnaX7w16lkSAdAqzqKlf1q+UAiZHj8SYVs8QCmqyCXbVOYaqENLpDzTpdpB8SXI8kCFaE8/u2sphRpKQdoxkwFzAVBgNVHSUBAf8ECzAJBgcogYxdBQECMAoGCCqGSM49BAMCA0gAMEUCIEZInaMVd267PbZkUrPhC+wKJ8i8OTx2sNU1k4QgIdbvAiEArj1ikPO4pBkbzy8H8SdueMKtDT4O70Qn9llNvmultTk="
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg/q/O39cBrXSmlATl7C3bcuPfikwuLkj0LSXVpdOdOwyhRANCAAQYYLYHnaX7w16lkSAdAqzqKlf1q+UAiZHj8SYVs8QCmqyCXbVOYaqENLpDzTpdpB8SXI8kCFaE8/u2sphRpKQd"
