# Example config

public_url = 'http://localhost:3001/'
internal_url = 'http://${SERVICES_HOST}:3002/'
store_url = 'postgres://postgres:postgres@localhost/wallet_server' # or 'memory://'

[wallet_server]
ip = '127.0.0.1'
port = 3001

[requester_server]
ip = "127.0.0.1"
port = 3002

# [requester_server.authentication]
# api_key = "your_secret_key"

[verifier]
trust_anchors = []

[verifier.usecases.driving_license]
certificate = "MIIBUTCB96ADAgECAhRl6OcmpjijxCkA1a76/tIvYLtmLDAKBggqhkjOPQQDAjAZMRcwFQYDVQQDDA5jYS5leGFtcGxlLmNvbTAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEwMTAwMDAwMFowGzEZMBcGA1UEAwwQY2VydC5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ/4iuWfQiqAh8PRmfUiM3wj/YMKwLsJ6xTYvT+2rdPW6SXqCOUOcqv7saSirWMKdjzYdfxKqAfSO9SI1Fv8my6jGTAXMBUGA1UdJQEB/wQLMAkGByiBjF0FAQIwCgYIKoZIzj0EAwIDSQAwRgIhAOKwEjS0R06oplVv1BNLNvd0U6cN/IedFLLpRbiIbyLBAiEApVM0esHuTunDjTkStRhlaTA/LFhjYhC+LOpNu5RFXfQ="
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgeWoxq6+7o1oiBXZvSfl91r1DaLWKJHjamWIOEY7aH0WhRANCAASf+Irln0IqgIfD0Zn1IjN8I/2DCsC7CesU2L0/tq3T1ukl6gjlDnKr+7Gkoq1jCnY82HX8SqgH0jvUiNRb/Jsu"

[verifier.usecases.parking_permit]
certificate = "MIIBUTCB+KADAgECAhUA11suNYBz8xIKnCjrw0S0aTzCMQIwCgYIKoZIzj0EAwIwGTEXMBUGA1UEAwwOY2EuZXhhbXBsZS5jb20wIBcNNzUwMTAxMDAwMDAwWhgPNDA5NjAxMDEwMDAwMDBaMBsxGTAXBgNVBAMMEGNlcnQuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQYYLYHnaX7w16lkSAdAqzqKlf1q+UAiZHj8SYVs8QCmqyCXbVOYaqENLpDzTpdpB8SXI8kCFaE8/u2sphRpKQdoxkwFzAVBgNVHSUBAf8ECzAJBgcogYxdBQECMAoGCCqGSM49BAMCA0gAMEUCIEZInaMVd267PbZkUrPhC+wKJ8i8OTx2sNU1k4QgIdbvAiEArj1ikPO4pBkbzy8H8SdueMKtDT4O70Qn9llNvmultTk="
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg/q/O39cBrXSmlATl7C3bcuPfikwuLkj0LSXVpdOdOwyhRANCAAQYYLYHnaX7w16lkSAdAqzqKlf1q+UAiZHj8SYVs8QCmqyCXbVOYaqENLpDzTpdpB8SXI8kCFaE8/u2sphRpKQd"

# If issuance is enabled

[issuer]
wte_issuer_pubkey = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExvHR3ALn7DoS1cZBiAs9XH77YdvWikZnBx2NILdgLMw6wx8NkLTIlfQHHjA7jmJaO3UD3YG/24vL0k9C0Og2pQ=="

[issuer.private_keys."com.example.pid"]
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg+wByjhVbYkQmtDbPfs8zvr4ekS0e2O61J2EqAJjer7GhRANCAASSrZcGMcO9RwDbVvEVKRq7+7CbCeO+jeEFcokj55c1h50cg3cYZGVCsQK2c39wphHm/oEhCFbDcFsgTIfAJ/x5"
certificate = "MIIBojCCAUmgAwIBAgIUUgzgQjkBVx5vK3umv6ktM2JklnAwCgYIKoZIzj0EAwIwGTEXMBUGA1UEAwwOY2EuZXhhbXBsZS5jb20wHhcNMjMxMjI2MDk1ODE3WhcNMjUwNTA5MDk1ODE3WjAaMRgwFgYDVQQDDA9waWQuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASSrZcGMcO9RwDbVvEVKRq7+7CbCeO+jeEFcokj55c1h50cg3cYZGVCsQK2c39wphHm/oEhCFbDcFsgTIfAJ/x5o24wbDALBgNVHQ8EBAMCB4AwEgYDVR0lBAswCQYHKIGMXQUBAjAJBgNVHRMEAjAAMB0GA1UdDgQWBBROJUSCukfgaRqz7Z8Y2+VvrAo0qDAfBgNVHSMEGDAWgBTzhh6coKts7wOjLAa5BwwwkK8UzzAKBggqhkjOPQQDAgNHADBEAiBQA+KRm1EPFvRGIpUOZGnXltFWKvKA8ax/M0piFD8WlwIgB4VtrkupOrDBALlzaKunJLO4ijD9tYgYqn8+HdLAaNY="
[issuer.private_keys."com.example.address"]
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg+wByjhVbYkQmtDbPfs8zvr4ekS0e2O61J2EqAJjer7GhRANCAASSrZcGMcO9RwDbVvEVKRq7+7CbCeO+jeEFcokj55c1h50cg3cYZGVCsQK2c39wphHm/oEhCFbDcFsgTIfAJ/x5"
certificate = "MIIBojCCAUmgAwIBAgIUUgzgQjkBVx5vK3umv6ktM2JklnAwCgYIKoZIzj0EAwIwGTEXMBUGA1UEAwwOY2EuZXhhbXBsZS5jb20wHhcNMjMxMjI2MDk1ODE3WhcNMjUwNTA5MDk1ODE3WjAaMRgwFgYDVQQDDA9waWQuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASSrZcGMcO9RwDbVvEVKRq7+7CbCeO+jeEFcokj55c1h50cg3cYZGVCsQK2c39wphHm/oEhCFbDcFsgTIfAJ/x5o24wbDALBgNVHQ8EBAMCB4AwEgYDVR0lBAswCQYHKIGMXQUBAjAJBgNVHRMEAjAAMB0GA1UdDgQWBBROJUSCukfgaRqz7Z8Y2+VvrAo0qDAfBgNVHSMEGDAWgBTzhh6coKts7wOjLAa5BwwwkK8UzzAKBggqhkjOPQQDAgNHADBEAiBQA+KRm1EPFvRGIpUOZGnXltFWKvKA8ax/M0piFD8WlwIgB4VtrkupOrDBALlzaKunJLO4ijD9tYgYqn8+HdLAaNY="

[issuer.digid]
client_id = "3e58016e-bc2e-40d5-b4b1-a3e25f6193b9"
issuer_url = "https://localhost:8006"
bsn_privkey = '{"d":"IBjaF3DVv0PWURtXyFKt534lVWT-hcocDtwi-oZoObCGv9jI6uJY7siQLLAbLHdkC7tOAf0Ui9Jl-C81ot2cNsUsYfCqcpHT9yT8WYuxygqoH1_9yPku_UhU-z4TfreS4_a71EBkHlBmCII7qXWCgaDrsl9CfhW2r2lXNbPh8ZC-OFEsdH7lKYW7-MlMLwJsRWyar6AYyxBFQ_5foK3fkaGtD-5Ca48ti5AgRw3Ca19KQNtp8sRnNujksgpRz0pMeOkoYK4l_dFZ83wdamha4rl-zOB-l1hoiD51L0Hvc-P7aj_QfkJjVoS3W3SnqOCkz9oaY7x1Ift-mk5QdUwoqQ","dp":"fhyxoeZDLNe6GTS7GT8OsK2UboJEIsCKkNdf-HIWwIUSKud7nZlQz1s1y2lbS_RKt-Z_nMnSwaw3mcJ-XvBr6FbUcLP0QVevRCgHHVQivMUM-fsjobawwYyiY5NZuB5UKS-EE7Fpv-IAbUzxMSAMWhtDOtuimBTFBROiDfVgKpk","dq":"EWyq4sGWzVBzupMi8eEEPe1ssdauYZT2SfETs6f1Al2mY2cP_Z-F-u3VwqzS65CHm7C3cR9fusUtR4sU3eQ5qcTbWSfbVob5ObLNkZDnf8orBoVNHCZHQb2U3QeKQ6dt0twZRIzYztN1E-ZHfd-iJaWSL9KZRe_OQA-F5XNzvyE","e":"AQAB","kty":"RSA","n":"wfpfys_ODMwGd4ytYqiYOMyxKNeHn3ZeIdJUF4WLcVxa30CEqdW6NYRVdpQeZUyQSev2nIEqmjYXKRAK6H_JVdCKsZWr59tHuSeAEA3FUZEWI2C0MPXLhViAvg-oM2TeiDcYA4vWumCktCayJI85BSB8J_El5DUoUVmrBxcVzkV02Ey1cvfnnlJ6UdDHil4XB1G4GjxI2uzV_9VEtjjj89WaI_HnfMQzx3N6iuYFXfQiMJ6C4Uf3zDTnBDehxEHUpCtZ8gxdjixQBnFnbm5nqU1VvDD6sg2NXz-ixd8dgVPzCg5qYGtrCRuojeoPoXQGT8I5yu_rvw04mirka4lE3Q","p":"7k0pGF1Gpyy26VaxlwqXaio2qlUQoyDN2vnMZ47MBOZXQnbtwSJkSPweXt7x8tgBry9-eHS8mV9Z_3-v8KNo7bFd-wcslZIojQEJDUmzfmpJWLrBMz_m5-ktVED2rHfQDG1tY9dESt9XO4YzOcB1lSmeCdaLIeHRu-B9qxGEMEk","q":"0GJ9izveUFDF1zYS66FcQpm49VHbA4UKCg-WFXkeAZ5-Xg8bgCoGd8T76bKG7pighi586MYc4HZ47tNb-zFPglwswP2YB5UakNGfyJ4iajcRmN4pLWD0CrC0oUe4xKg-hMLm_atqTw4ClgUEThExNE7ZAtbxE3vl1UqmKkssl_U","qi":"KSCnJClQlW3eqLFUogS4Wt4rfEmhJ1nbXXAoDaEs6nmCUqXh9aXS_4DwienUNIB8ZCSQM71eIbDLdlHN5Kk8G6Idhnq9CiZs9NTJLnet05HtaNd_Jm2ZM54uez-36bfEB6baf2d7oyF063nUeg14cOiwANvJNw8JLG0n4Rmvo34"}'
