[package]
name = "wallet_entity"
version.workspace = true
edition.workspace = true

[dependencies]
sea-orm = { version = "0.11.3", default-features = false, features = [
    "macros",
    "with-json",
] }
