.upload-browserstack-android-app:
  extends: .ruby-cache
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-ruby@sha256:d052bea8c1309494042a6b1e50b27fa2c31a577e1756edd6147b8ff545d4ac8b"
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
    FASTLANE_OPT_OUT_USAGE: "YES"
  script:
    - BROWSERSTACK_USER=$(kubectl get secret nl-wallet-browserstack -o jsonpath='{.data.user}' | base64 --decode)
    - export BROWSERSTACK_USER
    - BROWSERSTACK_KEY=$(kubectl get secret nl-wallet-browserstack -o jsonpath='{.data.key}' | base64 --decode)
    - export BROWSERSTACK_KEY
    - bundle install
    - |
      bundle exec fastlane android ci_browserstack \
        package_name:"${INTERNAL_APP_IDENTIFIER}${APP_PACKAGE_IDENTIFIER_SUFFIX:+.$APP_PACKAGE_IDENTIFIER_SUFFIX}" \
        version:"${RELEASE_VERSION}"

upload-browserstack-android-app-ont:
  extends: [.env-ont-k8s, .upload-browserstack-android-app]
  rules: !reference [.default-branch, rules]
  needs:
    - job: build-android-app-ont-profile
      artifacts: true
  variables:
    APP_PACKAGE_IDENTIFIER_SUFFIX: "latest"

upload-browserstack-android-app-demo:
  extends: [.env-ont-k8s, .upload-browserstack-android-app]
  rules: !reference [.release-tag, rules]
  needs:
    - job: build-android-app-demo-profile
      artifacts: true
  before_script:
    - !reference [.release-tag, before_script]
  variables:
    APP_PACKAGE_IDENTIFIER_SUFFIX: "demo"
