dependency-check:
  extends: .env-ont-k8s
  rules: !reference [.default-or-release-or-merge-request, rules]
  image:
    name: "$HARBOR_REGISTRY/$HARBOR_NLW_PROJECT/nl-wallet-app-builder-dependency-check@sha256:7578d0177b3ddba58d619a4a03dd0afa0427bf05e72d1a57e11db93a69211ad8"
  before_script:
    - NVD_API_KEY="$(kubectl get secret nl-wallet-nist-nvd -o jsonpath='{.data.api-key}' | base64 --decode)"
    - (cd wallet_web; npm ci)
    - mkdir -p $CI_PROJECT_DIR/dependency_check_data
  script:
    - dependency-check.sh
      --data $CI_PROJECT_DIR/dependency_check_data
      --disableDart
      --disableAssembly
      --disableYarnAudit
      --enableExperimental
      --format "HTML" --format "JSON" --format "XML"
      --scan "."
      --suppression $CI_PROJECT_DIR/dependency_check_suppressions.xml
      --nvdApiKey "$NVD_API_KEY"
      --failOnCVSS 0.1
  artifacts:
    when: always
    paths:
      - dependency-check-report.json
      - dependency-check-report.html
      - dependency-check-report.xml
  cache:
    key: dependency-check-${CI_JOB_NAME_SLUG}-${CI_DEFAULT_BRANCH}
    paths:
      - $CI_PROJECT_DIR/dependency_check_data
    policy: $CACHE_POLICY
  allow_failure: true

osv-scanner:
  rules: !reference [.default-or-release-or-merge-request, rules]
  image:
    name: "$HARBOR_REGISTRY/ghcr-io-proxy/google/osv-scanner:latest"
  script:
    - /osv-scanner --format sarif --recursive "$CI_PROJECT_DIR" > osv.sarif || /osv-scanner --format table --recursive "$CI_PROJECT_DIR"
  artifacts:
    when: always
    paths:
      - osv.sarif
  allow_failure: true

dependency-check-rust:
  rules: !reference [.default-or-release-or-merge-request, rules]
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-rust@sha256:4a4f49ce40693fbc9040869aa98822de3bfa87594ba7c7f25e5091f21a943fe5"
  before_script:
    - mkdir $CI_PROJECT_DIR/dependency_check_data
  script:
    # Note: RUSTSEC-2023-0071 is currently unfixable, a false positive and irrelevant for us, therefore we ignore it
    # Note: RUSTSEC-2024-0363 will be fixed when we upgrade `sea-orm` 1.1.0, which is not released yet
    - |
      cargo audit \
        --ignore RUSTSEC-2023-0071 \
        --ignore RUSTSEC-2024-0363 \
        --file wallet_core/Cargo.lock \
        --json | tee audit.json | jq
  artifacts:
    when: always
    paths:
      - audit.json
  allow_failure: true

dependency-check-images:
  rules: !reference [.default-or-release, rules]
  needs:
    - job: build-wallet-provider-image
      artifacts: false
    - job: build-wp-migrations-image
      artifacts: false
    - job: build-ws-migrations-image
      artifacts: false
    - job: build-mock-relying-party-image
      artifacts: false
    - job: build-wallet-server-image
      artifacts: false
    - job: build-verification-server-image
      artifacts: false
    - job: build-pid-issuer-image
      artifacts: false
  image:
    name: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-sonar-flutter@sha256:8bc288772cf98250e4fb6e741843d9455dc5a3c3d4505fe90ffb1a035f9aba50"
  variables:
    GIT_STRATEGY: none
  before_script:
    - IMAGES=(
      "nl-wallet-app-builder-android-flutter-rust"
      "nl-wallet-app-builder-flutter"
      "nl-wallet-app-builder-flutter-rust"
      "nl-wallet-app-builder-ruby"
      "nl-wallet-app-builder-rust"
      "nl-wallet-mock-relying-party"
      "nl-wallet-provider-migrations"
      "nl-wallet-provider"
      "nl-wallet-server-migrations"
      "nl-wallet-server"
      "nl-verification-server"
      "nl-pid-issuer"
      "nl-wallet-gba-hc-converter"
      )
    - mkdir -p trivy
  script:
    - |
      BASIC_AUTH="${HARBOR_GN2_ROBOT_NAME}:$(base64 --decode <<< ${HARBOR_GN2_ROBOT_SECRET})"
      for IMAGE in "${IMAGES[@]}"; do
        ARTIFACTS_URL="https://${HARBOR_REGISTRY}/api/v2.0/projects/${HARBOR_NLW_PROJECT}/repositories/${IMAGE}/artifacts?page_size=1&page=1&sort=-push_time"
        VULNERABILITIES_HREF=$(curl --user "${BASIC_AUTH}" --url "${ARTIFACTS_URL}" | jq ".[] | .addition_links.vulnerabilities.href" | sed -e 's/^"//' -e 's/"$//')
        VULNERABILITIES_URL="https://${HARBOR_REGISTRY}${VULNERABILITIES_HREF}"
        curl --user "${BASIC_AUTH}" -o "trivy/${IMAGE}.json" $VULNERABILITIES_URL
      done
  artifacts:
    paths:
      - trivy
