.wallet-config:
  script:
    - scripts/generate_wallet_config.sh "$APP_HOSTNAME" "$STATIC_HOSTNAME" "$CONFIG_PUBKEY" "$CONFIG_TLS_CA"
  artifacts:
    name: wallet-config-$WALLET_ENVIRONMENT
    paths:
      - wallet_core/wallet/wallet-config.json
      - wallet_core/wallet/config-server-config.json

wallet-config-ont:
  extends: .wallet-config
  rules: !reference [.default-branch, rules]
  variables:
    WALLET_ENVIRONMENT: ont
    APP_HOSTNAME: $APP_EXTERNAL_HOSTNAME_ONT
    STATIC_HOSTNAME: $STATIC_EXTERNAL_HOSTNAME_ONT
    CONFIG_PUBKEY: $WALLET_CONFIG_PUBKEY_ONT
    CONFIG_TLS_CA: $WALLET_CONFIG_TLS_CA_ONT

wallet-config-demo:
  extends: .wallet-config
  rules: !reference [.release-tag, rules]
  variables:
    WALLET_ENVIRONMENT: demo
    APP_HOSTNAME: $APP_EXTERNAL_HOSTNAME_DEMO
    STATIC_HOSTNAME: $STATIC_EXTERNAL_HOSTNAME_DEMO
    CONFIG_PUBKEY: $WALLET_CONFIG_PUBKEY_DEMO
    CONFIG_TLS_CA: $WALLET_CONFIG_TLS_CA_DEMO

wallet-config-acceptance:
  extends: .wallet-config
  rules: !reference [.release-tag, rules]
  when: manual
  variables:
    WALLET_ENVIRONMENT: acceptance
    APP_HOSTNAME: $APP_EXTERNAL_HOSTNAME_ACC
    STATIC_HOSTNAME: $STATIC_EXTERNAL_HOSTNAME_ACC
    CONFIG_PUBKEY: $WALLET_CONFIG_PUBKEY_ACC
    CONFIG_TLS_CA: $WALLET_CONFIG_TLS_CA_ACC

wallet-config-preproduction:
  extends: .wallet-config
  rules: !reference [.release-tag, rules]
  when: manual
  variables:
    WALLET_ENVIRONMENT: preproduction
    APP_HOSTNAME: $APP_EXTERNAL_HOSTNAME_PREPROD
    STATIC_HOSTNAME: $STATIC_EXTERNAL_HOSTNAME_PREPROD
    CONFIG_PUBKEY: $WALLET_CONFIG_PUBKEY_PREPROD
    CONFIG_TLS_CA: $WALLET_CONFIG_TLS_CA_PREPROD

wallet-config-production:
  extends: .wallet-config
  rules: !reference [.release-tag, rules]
  when: manual
  variables:
    WALLET_ENVIRONMENT: production
    APP_HOSTNAME: $APP_EXTERNAL_HOSTNAME_PROD
    STATIC_HOSTNAME: $STATIC_EXTERNAL_HOSTNAME_PROD
    CONFIG_PUBKEY: $WALLET_CONFIG_PUBKEY_PROD
    CONFIG_TLS_CA: $WALLET_CONFIG_TLS_CA_PROD
