.wallet-env-config:
  script:
    - deploy/generate_wallet_env_config.sh "$APP_HOSTNAME" "$STATIC_HOSTNAME" "$CONFIG_PUBKEY" "$CONFIG_TLS_CA" >wallet_core/wallet/.env
  artifacts:
    name: wallet-env-config-$WALLET_ENVIRONMENT
    paths:
      - wallet_core/wallet/.env

wallet-env-config-ont:
  extends: .wallet-env-config
  rules: !reference [.default-branch, rules]
  variables:
    WALLET_ENVIRONMENT: ont
    APP_HOSTNAME: $APP_EXTERNAL_HOSTNAME_ONT
    STATIC_HOSTNAME: $STATIC_EXTERNAL_HOSTNAME_ONT
    CONFIG_PUBKEY: $WALLET_CONFIG_PUBKEY_ONT
    CONFIG_TLS_CA: $WALLET_CONFIG_TLS_CA_ONT    

wallet-env-config-demo:
  extends: .wallet-env-config
  rules: !reference [.release-tag, rules]
  variables:
    WALLET_ENVIRONMENT: demo
    APP_HOSTNAME: $APP_EXTERNAL_HOSTNAME_DEMO
    STATIC_HOSTNAME: $STATIC_EXTERNAL_HOSTNAME_DEMO
    CONFIG_PUBKEY: $WALLET_CONFIG_PUBKEY_DEMO
    CONFIG_TLS_CA: $WALLET_CONFIG_TLS_CA_DEMO   
