[workspace]
members = ["wallet", "flutter_api", "platform_support", "wallet_shared"]
exclude = ["flutter_rust_bridge_codegen", "uniffi-bindgen"]

[workspace.package]
version = "0.1.0"
edition = "2021"
