[package]
name = "platform_support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
hardware = ["dep:uniffi"]
software = ["wallet_common/software"]
integration-test = []
hardware-integration-test = ["integration-test", "hardware", "dep:jni"]

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
wallet_common = { path = "../wallet_common" }
jni = { workspace = true, optional = true }
never.workspace = true
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
thiserror.workspace = true
uniffi = { workspace = true, optional = true }

[dev-dependencies]
platform_support = { path = ".", features = ["software", "integration-test"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"], optional = true }
