[package]
name = "platform_support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
software = ["wallet_common/software-keys"]
integration-test = ["wallet_common/integration-test"]
hardware-integration-test = ["integration-test", "dep:jni"]

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
wallet_common = { path = "../wallet_common" }
jni = { workspace = true, optional = true }
never.workspace = true
once_cell = { workspace = true }
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
thiserror.workspace = true
uniffi = { workspace = true }

[dev-dependencies]
platform_support = { path = ".", features = ["software", "integration-test"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
