[package]
name = "platform_support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "lib"]
doctest = false

[features]
# Implement the PlatformEcdsaKey trait on SoftwareEcdsaKey
software = ["wallet_common/software-keys"]
# Enable helper code for integration tests
integration-test = [
    "wallet_common/integration-test",
    "tokio/fs",
    "tokio/io-util",
]
# Enable helper code for iOS and Android integration tests
hardware-integration-test = ["integration-test", "dep:jni"]

[dependencies]
once_cell.workspace = true
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "parking_lot"] }
uniffi.workspace = true

jni = { workspace = true, optional = true }

wallet_common.path = "../wallet_common"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "fs", "io-util"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
