[package]
name = "platform_support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[features]
software = ["wallet_common/software-keys"]
integration-test = [
    "wallet_common/integration-test",
    "tokio/fs",
    "tokio/io-util",
]
hardware-integration-test = ["integration-test", "dep:jni"]

[dependencies]
async-trait.workspace = true
once_cell.workspace = true
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "parking_lot"] }
uniffi.workspace = true

jni = { workspace = true, optional = true }

wallet_common.path = "../wallet_common"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

platform_support = { path = ".", features = ["software", "integration-test"] }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
