[package]
name = "platform_support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
hardware = ["dep:once_cell", "dep:uniffi"]
software = ["dep:aes-gcm", "dep:once_cell", "dep:rand_core"]
integration-test = []
hardware-integration-test = ["integration-test", "hardware", "dep:jni"]
software-integration-test = ["integration-test", "software"]

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
wallet_common = { path = "../wallet_common" }
aes-gcm = { workspace = true, optional = true }
jni = { workspace = true, optional = true }
never.workspace = true
once_cell = { workspace = true, optional = true }
p256 = { workspace = true, features = ["ecdsa", "pkcs8", "std"] }
pkcs8 = { workspace = true, features = ["std"] }
rand_core = { workspace = true, optional = true }
thiserror.workspace = true
uniffi = { workspace = true, optional = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"], optional = true }
