[package]
name = "platform_support"
version.workspace = true
edition.workspace = true

[features]
hardware = ["dep:once_cell", "dep:uniffi"]
software = ["dep:aes-gcm", "dep:once_cell", "dep:rand_core"]
integration-test = []
hardware-integration-test = ["integration-test", "hardware", "dep:jni"]
software-integration-test = ["integration-test", "software"]

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
wallet_common = { path = "../wallet_common" }
aes-gcm = { version = "0.10.1", optional = true }
jni = { version = "0.21.1", optional = true }
never = "0.1.0"
once_cell = { version = "1.17.1", optional = true }
p256 = "0.12.0"
rand_core = { version = "0.6.4", optional = true }
spki = { version = "0.6.0", features = ["std"] }
thiserror = "1.0.38"
uniffi = { version = "0.23.0", optional = true }

[build-dependencies]
uniffi = { version = "0.23.0", features = ["build"], optional = true }
