[package]
name = "wallet"
version.workspace = true
edition.workspace = true

[dependencies]
wallet_common = { path = "../wallet_common" }
wallet_migration = { path = "../wallet_migration" }
anyhow = "1.0.66"
libsqlite3-sys = { version = "0.24.2", features = [
    "bundled-sqlcipher-vendored-openssl",
] }
p256 = { version = "0.12.0" }
tokio = { version = "1.27.0", features = ["full"] }
reqwest = { version = "0.11.16", default-features = false, features = [
    "json",
    "blocking",
    "rustls-tls-webpki-roots",
] }
ring = "0.16.20"
sea-orm = { version = "0.11.3", default-features = false, features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
    "with-json",
] }
thiserror = "1.0.39"

# TODO: find a proper way to talk to the wallet provider instead of this
wallet_provider = { path = "../wallet_provider" }

# enable the "hardware" feature for platform_support when building for either Android or iOS
[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
platform_support = { path = "../platform_support", features = ["hardware"] }

# enable the "software" feature for platform_support when NOT building for either Android or iOS
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
platform_support = { path = "../platform_support", features = ["software"] }

# enable the "software-integration-test" feature for platform_support when running tests,
# which includes the "software" feature
[dev-dependencies]
platform_support = { path = "../platform_support", features = [
    "software-integration-test",
] }
tempfile = "3.5.0"
