[package]
name = "wallet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[features]
# Allow the disclosure return URL and its prefix to use http://
allow_http_return_url = ["nl_wallet_mdoc/allow_http_return_url"]
# Skip TLS certificate validation for HTTP requests
disable_tls_validation = []
# Read an .env file with configuration overrides when compiling
env_config = ["dep:dotenvy"]
# Include mock implementations and constructors for testing
mock = ["dep:mockall", "nl_wallet_mdoc/mdocs_map", "nl_wallet_mdoc/mock", "openid4vc/mock"]
# Export the traits and actual implementations of the Wallet dependencies
wallet_deps = []

[dependencies]
base64.workspace = true
chrono = { workspace = true, features = ["std", "clock"] }
ciborium.workspace = true
futures.workspace = true
jsonwebtoken.workspace = true
http.workspace = true
indexmap.workspace = true
itertools.workspace = true
libsqlite3-sys = { workspace = true, features = [
    "bundled-sqlcipher-vendored-openssl",
] }
mime.workspace = true
once_cell.workspace = true
openid = { workspace = true, features = ["rustls"] }
p256 = { workspace = true, features = ["ecdsa", "std"] }
reqwest = { workspace = true, features = ["json", "rustls-tls-webpki-roots"] }
ring = { workspace = true, features = ["std"] }
sea-orm = { workspace = true, features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "with-uuid",
] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_urlencoded.workspace = true
serde_with = { workspace = true, features = ["base64"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "fs"] }
tracing.workspace = true
trait-variant.workspace = true
url.workspace = true
uuid = { workspace = true, features = ["v4"] }

mockall = { workspace = true, optional = true }

entity.path = "entity"
migration.path = "migration"
nl_wallet_mdoc.path = "../mdoc"
openid4vc.path = "../openid4vc"
platform_support.path = "../platform_support"
wallet_common.path = "../wallet_common"

[dev-dependencies]
assert_matches.workspace = true
jsonwebtoken.workspace = true
mockall.workspace = true
rand_core.workspace = true
rstest.workspace = true
serial_test.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "test-util"] }
wiremock.workspace = true

nl_wallet_mdoc = { path = "../mdoc", features = [
    "generate",
    "examples",
    "software_keys",
    "mdocs_map",
    "test",
    "mock",
] }
openid4vc = { path = "../openid4vc", features = ["mock"] }
# enable the "software" feature for platform_support when running tests
platform_support = { path = "../platform_support", features = ["software"] }
wallet_common = { path = "../wallet_common", features = ["mock_p256_keys"] }

[build-dependencies]
dotenvy = { workspace = true, optional = true }
