[package]
name = "gba_hc_converter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "gba_hc_converter"

[lib]
doctest = false

[dependencies]
axum = { workspace = true, features = ["http1", "json", "tokio", "tower-log", "tracing"] }
config = { workspace = true, features = ["toml"] }
csv.workspace = true
http.workspace = true
indexmap.workspace = true
lazy_static.workspace = true
nutype = { workspace = true, features = ["regex", "serde"] }
once_cell = { workspace = true, features = ["parking_lot"] }
pem.workspace = true
quick-xml = { workspace = true, features = ["async-tokio", "serialize", "overlapped-lists"] }
regex.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls-webpki-roots"] }
sentry = { workspace = true, features = [
    "backtrace",
    "contexts",
    "debug-images",
    "panic",
    "anyhow",
    "reqwest",
    "rustls",
    "tracing",
    "log",
] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with = { workspace = true, features = ["base64"] }
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "parking_lot", "fs", "net"] }
tower-http = { workspace = true, features = ["trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "parking_lot", "json"] }
trait-variant.workspace = true

wallet_common = { path = "../wallet_common", features = ["sentry"] }

[dev-dependencies]
assert-json-diff.workspace = true
ctor.workspace = true
rstest.workspace = true
tokio = { workspace = true, features = ["macros"] }
