[advisories]
ignore = [
    "RUSTSEC-2023-0071", # The vulnerability pertains to the use of RSA private keys in the rsa crate. We only use this crate to evaluate RSA public keys as found in Google CA certificates.
]
