[[IgnoredVulns]]
id = "RUSTSEC-2023-0071"
ignoreUntil = 2025-03-01
reason = "rsa is a dependency of sqlx-mysql which is not used"

[[IgnoredVulns]]
id = "RUSTSEC-2021-0145"
ignoreUntil = 2025-03-01
reason = "potential unaligned read, but only on Windows, so suppressing here"

[[IgnoredVulns]]
id = "RUSTSEC-2024-0375"
ignoreUntil = 2025-03-01
reason = "atty is unmaintained but contains no vulnerabilities and is a transitive dependency of flutter_rust_bridge_codegen which should be updated first. There is an issue on the backlog, so suppressing for now."

[[IgnoredVulns]]
id = "RUSTSEC-2024-0320"
ignoreUntil = 2025-03-01
reason = "serde_yaml is unmaintained but contains no vulnerabilities and should be reported to flutter_rust_bridge. There is an issue on the backlog, so suppressing for now."
