[package]
name = "tests_integration_performance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
local = [
    "nl_wallet_mdoc/allow_http_return_url",
]

[dependencies]
indexmap.workspace = true
reqwest = { workspace = true, features = ["rustls-tls-webpki-roots"] }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "parking_lot",
    "macros",
] }
url.workspace = true
uuid.workspace = true
tracing.workspace = true

nl_wallet_mdoc = { path = "../../mdoc" }
openid4vc = { path = "../../openid4vc" }
platform_support = { path = "../../platform_support", features = ["software"] }
tests_integration_common = { path = "../common" }
wallet = { path = "../../wallet", features = [
    "mock",
    "wallet_deps",
    "env_config",
] }
wallet_common.path = "../../wallet_common"
wallet_server = { path = "../../wallet_server" }

[build-dependencies]
dotenvy.workspace = true
