[package]
name = "wallet_provider_domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[features]
# Include mock implementations and constructors for testing
mock = ["dashmap", "hmac", "rand", "sha2"]

[dependencies]
chrono = { workspace = true, features = ["std", "clock", "serde"] }
dashmap = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["debug"] }
futures = { workspace = true, features = ["std", "async-await"] }
hmac = { workspace = true, optional = true, features = ["std"] }
p256 = { workspace = true, features = ["ecdsa", "std"] }
rand = { workspace = true, optional = true }
serde.workspace = true
sha2 = { workspace = true, optional = true }
thiserror.workspace = true
uuid = { workspace = true, features = ["v4"] }

wallet_common.path = "../../wallet_common"
