[package]
name = "wallet_provider_domain"
version.workspace = true
edition.workspace = true

[features]
stub = []

[dependencies]
wallet_common = { path = "../../wallet_common" }
p256 = { workspace = true }

async-trait.workspace = true
chrono = { workspace = true, features = ["default", "serde"] }
thiserror.workspace = true
serde.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }
