[package]
name = "wallet_provider_domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
mock = ["dashmap", "rand"]

[dependencies]
async-trait.workspace = true
chrono = { workspace = true, features = ["std", "clock", "serde"] }
dashmap = { workspace = true, optional = true }
futures.workspace = true
p256 = { workspace = true, features = ["ecdsa", "std"] }
rand = { workspace = true, optional = true }
serde.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["serde", "v4"] }

wallet_common.path = "../../wallet_common"
