[package]
name = "hsm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
mock = [
     "dep:dashmap",
     "dep:hmac",
     "dep:rand",
     "dep:sha2",
     "dep:wallet_common"
]

[dependencies]
# Include mock implementations and constructors for testing
p256 = { workspace = true, features = ["ecdsa", "std"] }

dashmap = { workspace = true, optional = true }
hmac = { workspace = true, optional = true, features = ["std"] }
rand = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }

wallet_common = { path = "../wallet_common", optional = true }
