apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrp-verification-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mrp-verification-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: mrp-verification-server
        tier: vertrouwd
        egress-frontoffice-policy: allow
        ingress-controller-frontoffice-policy: allow
        db-mrp-in-zeer-vertrouwd: allow
    spec:
      imagePullSecrets:
        - name: harbor-puller
      containers:
        - name: mrp-verification-server
          image: $MRP_VERIFICATION_SERVER_IMAGE
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "300m"
          ports:
            - name: wallet-port
              containerPort: 3001
            - name: requester-port
              containerPort: 3002
          volumeMounts:
            - name: config-volume
              mountPath: /verification_server.toml
              subPath: config.toml
          env:
            - name: VERIFICATION_SERVER_WALLET_SERVER__PORT
              value: "3001"
            - name: VERIFICATION_SERVER_REQUESTER_SERVER__IP
              value: "0.0.0.0"
            - name: VERIFICATION_SERVER_REQUESTER_SERVER__PORT
              value: "3002"
            - name: VERIFICATION_SERVER_PUBLIC_URL
              value: "https://${MRP_VERIFICATION_SERVER_EXTERNAL_HOSTNAME}/${MRP_VERIFICATION_SERVER_EXTERNAL_CONTEXT_PATH}/"
            - name: VERIFICATION_SERVER_UNIVERSAL_LINK_BASE_URL
              value: "${UNIVERSAL_LINK_BASE}"
            - name: VERIFICATION_SERVER_STRUCTURED_LOGGING
              value: "true"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-mrp-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-mrp-app
                  key: password
            - name: VERIFICATION_SERVER_STORAGE__URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@db-cluster-mrp-rw:5432/verification_server"
            - name: RUST_LOG
              value: "debug,hyper=warn"
      volumes:
        - name: config-volume
          secret:
            secretName: nl-mrp-verification-server-config
