---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "${RELYING_PARTY_URL}/"
    includePaths:
    - "${RELYING_PARTY_URL}/.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- alertFilters:
# False positive analysis in pwv-3375 showed that this is not a vulnerability
    - ruleId: "10202"
      ruleName: "Absence of Anti-CSRF Tokens (10202)"
      context: ""
      newRisk: "False Positive"
      parameter: ""
      parameterRegex: false
      url: ""
      urlRegex: false
      attack: ""
      attackRegex: false
      evidence: ""
      evidenceRegex: false
      methods: []
# False positive analysis in pwv-3375 showed that this is not a vulnerability
    - ruleId: "20012"
      ruleName: "Anti-CSRF Tokens Check (20012)"
      context: ""
      newRisk: "False Positive"
      parameter: ""
      parameterRegex: false
      url: ""
      urlRegex: false
      attack: ""
      attackRegex: false
      evidence: ""
      evidenceRegex: false
      methods: []
# TODO: PVW-3692: Blocked until https://github.com/zaproxy/zap-extensions/pull/5957 gets merged and released. The rule is still in beta and the finding has low risk, therefore it is acceptable to ignore it for now.
    - ruleId: "90004"
      ruleName: "Insufficient Site Isolation Against Spectre Vulnerability (20012)"
      context: ""
      newRisk: "TODO Low"
      parameter: ""
      parameterRegex: false
      url: ""
      urlRegex: false
      attack: ""
      attackRegex: false
      evidence: ""
      evidenceRegex: false
      methods: []
# False positive analysis in pwv-3375 showed that this is not a vulnerability
    - ruleId: "40025"
      ruleName: "Proxy Disclosure (40025)"
      context: ""
      newRisk: "False Positive"
      parameter: ""
      parameterRegex: false
      url: ""
      urlRegex: false
      attack: ""
      attackRegex: false
      evidence: ""
      evidenceRegex: false
      methods: []
  parameters:
    deleteGlobalAlerts: false
  name: "alertFilter"
  type: "alertFilter"
- parameters:
    maxAlertsPerRule: 0
    scanOnlyInScope: true
    maxBodySizeInBytesToScan: 0
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: "Default Context"
    user: ""
    url: ""
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 20
    type: "stats"
    name: "At least 20 URLs found"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    context: "Default Context"
    user: ""
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
    addQueryParam: false
    delayInMs: 0
    handleAntiCSRFTokens: false
    injectPluginIdInHeader: false
    scanHeadersAllRequests: false
    threadPerHost: 24
    maxAlertsPerRule: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "modern"
    theme: "console"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: ""
    reportTitle: "RELYING_PARTY ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "passingrules"
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  - "params"
  - "chart"
  - "statistics"
  sites: []
  name: "report"
  type: "report"
- parameters:
    template: "traditional-xml"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: "RELYING_PARTY-zap.xml"
    reportTitle: "RELYING_PARTY ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sites: []
  name: "report"
  type: "report"
- parameters:
    template: "traditional-json"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: "RELYING_PARTY-zap.json"
    reportTitle: "RELYING_PARTY ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
    - "info"
    - "low"
    - "medium"
    - "high"
  confidences:
    - "falsepositive"
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  sites: []
  name: "report"
  type: "report"


