[package]
name = "wallet_common_macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
rstest.workspace = true
trybuild = { workspace = true, features = ["diff"] }

wallet_common.path = "../"
